### ISSUE TITLE
Evaluate hardware apps 

### ISSUE THREAD

**Issue by Pierre-Gilles** [blockstack/app-mining#107]
Following our discussion in https://github.com/blockstack/app-mining/issues/91, I opened this issue to find a way to evaluate hardware apps with reviewers like Digital Right reviewers.

My reply to the previous thread:

Hey @larrysalibra,

Sure, I completely understand your approach.

About the Docker version, it's an official way of deploying Gladys. Many users use Gladys on a Synology NAS (x86 arch) and they deploy Gladys with Docker since years.

So it's as good as using our Raspbian image, both ways are as official. 

Even more, our next release will be deployed using Docker everywhere, even on Raspberry Pi with Docker on ARM, so it'll not be a question anymore :)

**Comment by friedger** [comment]
Hopefully, there will be more IoT devices that use blockstack auth.

One possible solution, would be that the device makers submit a simulation app ("Experience the device online") to the app mining program, not the device itself. For Gladys, @Pierre-Gilles could submit https://demo.gladysassistant.com (maybe with a landing page only for the demonstrator app)

**Comment by Pierre-Gilles** [comment]
@larrysalibra I worked this weekend on an easy process for you to test Gladys using docker-compose. You just have to run a simple docker-compose command to start a whole Gladys setup on your machine. This is the official Docker image used by many users, so it's a real setup.

1. Install Docker for your system (ex: [Docker for Mac](https://hub.docker.com/editions/community/docker-ce-desktop-mac) )

2. Download this [docker-compose.yml](https://gist.github.com/Pierre-Gilles/44d799fc373c32071694e9861e18bb1e). This is Gladys v3.14.0, the current running version used by all Gladys users. This is the official [gladysassistant/gladys](https://cloud.docker.com/u/gladysassistant/repository/docker/gladysassistant/gladys) Docker image, used by many users on VM or Synology NAS. (it's not Gladys 4, the future version I've been talking about)

3. Place this docker-compose file inside a folder, and in a terminal simply run:

```
 docker-compose up -d
```

4. Access `localhost:8080` and voilà :)  

5. You should see the following signup process:

<img width="1552" alt="Screenshot 2019-05-20 at 07 53 26" src="https://user-images.githubusercontent.com/7365207/57989966-6359dd80-7ad4-11e9-91f7-ba940cb9dc0c.png">

<img width="1552" alt="Screenshot 2019-05-20 at 07 45 24" src="https://user-images.githubusercontent.com/7365207/57989895-cb5bf400-7ad3-11e9-802c-8b2c01ba7806.png">

<img width="1552" alt="Screenshot 2019-05-20 at 07 45 56" src="https://user-images.githubusercontent.com/7365207/57989898-d020a800-7ad3-11e9-8ea8-33687b42acdf.png">

<img width="1552" alt="Screenshot 2019-05-20 at 07 46 05" src="https://user-images.githubusercontent.com/7365207/57989899-d31b9880-7ad3-11e9-820b-17b7b8811006.png">

6. If you are interested in the code, the code is located [here](https://github.com/GladysAssistant/Gladys/blob/master/assets/js/app/installation/installation.controller.js#L213) and [here](https://github.com/GladysAssistant/Gladys/blob/master/assets/js/app/blockstack/blockstack.service.js).

@friedger As Gladys 4 is not ready yet, I decided to implement the same Blockstack integration of Gladys 4 in Gladys 3! So now the separate module is no longer needed. ;) 

I really hope it's going to work before next month, let me know if you face any issue.

**Comment by larrysalibra** [comment]
Bringing forward my comments from earlier: 

> Evaluating demo versions of apps doesn't seem fair to other developers that have had their apps reviewed in the same environment in which users actually use it. Reviewing an app in an entirely different environment/form factor and hardware than users are intended to use it doesn't seem incredibly useful to me.

I'd like to hear input from others besides @Pierre-Gilles and @friedger

**Comment by larrysalibra** [comment]
Talked this over with the PBC team. 

We're only going to evaluate apps that normal users consider apps. This means running docker (or some other special software) to use the software is a no go. Hosted demo apps that aren't intended to be used in that method by end users are also a no go.

**Comment by friedger** [comment]
So, simulators for end-users who want to try before buy should work.

**Comment by larrysalibra** [comment]
> So, simulators for end-users who want to try before buy should work.

No.

**Comment by Pierre-Gilles** [comment]
So the conclusion to this topic is that Blockstack don't accept hardware apps anymore right?
I guess desktop electron apps are not accepted as well so?

It should be added to the requirement then and in the changelog.

It's a little sad but I guess Blockstack PBC knows the direction they want to bring the company to.

I guess I should have just built a ping-pong or todo web app :)

**Comment by friedger** [comment]
Flight simulators don't work?
