### ISSUE TITLE
Awario Auditing

### ISSUE THREAD

**Issue by AnthonyRonning** [blockstack/app-mining#108]
**What is the problem you are seeing? Please describe.**
So far, everything has been audit-able and clear to understand, except Awario. If I want to look up how many upvotes an app has, I can look at it directly. If I want to add up the score on how well an app uses blockstack functionality, I can look at their open source & try out there app to add up the score myself. The TMUI I can't look at, but I have no reason to believe that the scoring would be a lie, it's very subjective as it is anyways. 

However, I absolutely do not believe an app with 180 tweets has 1.5 million reach, and I want to see how and why that is. 

**How is this problem misaligned with goals of app mining?**
I do not believe the system isn't being gamed here, and I do not trust this new reviewer enough to take some random numbers. People have been gaming social media reach since the conception of it. Show us where they are coming up with these numbers or don't have them as a reviewer at all. 

**What is the explicit recommendation you’re looking to propose?**
Allow us to audit Awario.

**Describe your long term considerations in proposing this change. Please include the ways you can predict this recommendation could go wrong and possible ways mitigate.**
We're putting a lot of trust in blockstack & random reviewers without the ability to audit, and even though I think Awario is a stupid metric in the first place, the fact that we have no idea where they are getting their numbers is beyond me. If more apps keep getting introduced that the community cannot audit, then this is not a community aligned project. 

We've already seen multiple times where the spreadsheet numbers have been incorrect, thanks to community auditing. Now tell me that community audits are not beneficial.

**Comment by ViniciusBP** [comment]
This might help you understand why we had that reach:

. Mike Cernovich, 446k followers, documentary filmmaker, best-selling author, and journalist: https://bit.ly/2NbjPCS

. Francis Pouliot, 44k followers, CEO of Bitcoin Bull: https://bit.ly/2GseR47

. Cynthia McKinney, 36k followers, Former Congresswoman: http://bit.ly/2S7SbHJ

. Suzie Dawson, 22K followers, President of InternetPartyNz: http://bit.ly/2GMVFNE

**Comment by thedavidlewis** [comment]
Kudos!

> This might help you understand why we had that reach:
> 
> . Mike Cernovich, 446k followers, documentary filmmaker, best-selling author, and journalist: https://bit.ly/2NbjPCS
> 
> . Francis Pouliot, 44k followers, CEO of Bitcoin Bull: https://bit.ly/2GseR47
> 
> . Cynthia McKinney, 36k followers, Former Congresswoman: http://bit.ly/2S7SbHJ
> 
> . Suzie Dawson, 22K followers, President of InternetPartyNz: http://bit.ly/2GMVFNE

**Comment by thedavidlewis** [comment]
Any word on when we'll be able to see our own Awario dashboard? I think seeing how our own apps were scored will be a great start.

**Comment by friedger** [comment]
There is the spreadsheet with all data https://docs.google.com/spreadsheets/d/1m5_b8NjCGM0FW0S8X_QFBeL3r7OoypsF_ZcVz4FRv38/htmlview#gid=0

**Comment by AnthonyRonning** [comment]
@friedger that's perfect actually. But where did you get it from and why was it not sent out with the scoring spreadsheet?

**Comment by cuevasm** [comment]
Hey again, I believe @hstove provided this at the time, having them auditable was always the intent and everyone's spreadsheets and report summaries are [publicly available](https://docs.google.com/spreadsheets/d/1m5_b8NjCGM0FW0S8X_QFBeL3r7OoypsF_ZcVz4FRv38/edit?usp=sharing). Did you have a chance to read through the [details about this score](https://github.com/blockstack/app-mining/issues/30#issuecomment-479499261) (also available in the docs)? 

In the coming month or two, you'll be getting direct access to Awario itself (vs. spreadsheets) so auditing will be even easier then. 

I also personally audited hundreds and hundreds of mentions and am pretty confident in those that made it through - some were also then reported by the community and I investigated those and made adjustments as necessary. As described above in that link, everyone has this audit/reporting right and I look at all reported. Inevitably, some Mentions will slip through, however I've noticed that on the whole this doesn't impact things too drastically. 

Just to be clear, there is literally no data I get on the Awario side that isn't directly shared with everyone.

**Comment by AnthonyRonning** [comment]
Yes, as @friedger pointed out, this magical link that has not been shared with all app miners now gives me access to view the reports. The reports satisfy this ticket, but sharing these reports with the developers is the problem. 

Every month, @hstove emails out the scoring spreadsheet for us to audit, but the awario spreadsheet was not shared, and thus not audited by every app miner. 

If people agree to share the awario spreedsheet for next month and the months to come until we have access to awario, then I'm happy and this can be closed.

**Comment by friedger** [comment]
The link was shared in https://github.com/blockstack/app-mining/issues/30#issuecomment-484967067
It should go into the doc, I have added a comment to the relevant isssue: https://github.com/blockstack/docs.blockstack/issues/164#issuecomment-493704805

**Comment by moxiegirl** [comment]
@friedger That issue you added to should have been closed. The Awario material was in the docs weeks ago. Here is an issue to represent what you are asking for.

https://github.com/blockstack/docs.blockstack/issues/254

**Comment by jeffdomke** [comment]
Sounds like the sheet was shared and we need to include the Awario data at the start of the audit period. Next step forward here will be App Miners getting a login to explore the data on the Awario platform. Marking as done.

**Comment by GinaAbrams** [comment]
Added to changelog.
