### ISSUE TITLE
Awario encourage to use centralized, privately owned services

### ISSUE THREAD

**Issue by friedger** [blockstack/app-mining#109]
**What is the problem you are seeing? Please describe.**
App publishers that want to raise awareness of their apps and blockstack in general are encouraged to use the centralized services Twitter, Youtube, Facebook, Instagram.

**How is this problem misaligned with goals of app mining?**
App developers are discouraged to build apps that compete with these services. App users are discouraged to use Blockstack apps competing with these services.

**What is the explicit recommendation you’re looking to propose?**
Add a new score ("decentralized score") to awario final score. When building the average of the centralized (current score) and the decentralized score, the centr. score gets the factor 0.9, the decentr. score the factor 0.1.
The decentralized score consists of
- [ ] reach of mention in debutapp.social
- [ ] reach of mention in a peertube and mastodon instance that was setup for blockstack.

**Describe your long term considerations in proposing this change. Please include the ways you can predict this recommendation could go wrong and possible ways mitigate.**
* More Blockstack apps should be added in the future.
* The factors should be changed in favor of the decentralized score.
* When collections are available an indexer should be setup that helps awario to aggregate data.

**Additional context**
https://github.com/blockstack/app-mining/issues/30#issuecomment-464126459

**Comment by jeffdomke** [comment]
@cuevasm feel free to add context here. My sense is that we can suggest many things to Awario but we can't force them to monitor new services?

**Comment by cuevasm** [comment]
Totally love the spirit here, but yes to Jeff's point, this would be really tough to accomplish right now. I think from Awario's perspective it's a bit early to start adding the ability to track decentralized social networks (they just don't have the volume to be interesting to them or their other clientele). I'm also not sure of anyone else that could do it either off the top of my head. I do reall like the idea of encouraging App Miners to be posting on decentralized social networks, but I think there is a rabbit hole of privacy and tracking issues there to be solved first - seems like something the majority of these networks just woudn't allow for any kind of API access to for capturing Mentions.

I will also say that there is a separation here that needs to be made between the idea of using apps and marketing apps. While it's true that we prefer if people stopped using centralized networks, that isn't to say that they can't be used very effectively to market and accelerate the adoption of dapps. They have critical mass and are an important, probably necessary, part of bringing dapps to the mainstream. I actually see it as a major reason why dapp adoption will happen more quickly than we expect - the networks between people are already there and we can highjack them and convert them to promote dapps. 

What are the biggest decentralized social networks currently? I am thinking about Diaspora, Minds, Mastodon, Sola...

**Comment by dantrevino** [comment]
Agree with all that @cuevasm said, and I would add .. the reality is that with the current state of decentralized apps, NONE are not conducive to communication outside of our little bubble.  None of the "blog" apps are at all useful for SEO ... and yeah I get the irony of being a slave to the centralized ad services ... but we're not going to gain traction by talking to ourselves.

I'd love to start this discussion with Awario at some point, but we have a lot of work to do in the decentralized ecosystem first.

**Comment by friedger** [comment]
Decentralized network: Steemit 

@dantrevino I think starting early makes blockstack much more credible. I agree that many apps need many improvements.
