### ISSUE TITLE
Proposal to exclude clone apps in app mining. 

### ISSUE THREAD

**Issue by GinaAbrams** [blockstack/app-mining#113]
**What is the problem you are seeing? Please describe.**
While we're interested in encouraging multiple apps in the same category, and significant upgrades to existing apps, cloned apps are a waste of app reviewers and app mining operator's time. This rule reflects existing app store policies. For example, Apple does not allow duplicates of the same exact app in the Apple App store.  

**What is the explicit recommendation you’re looking to propose?**
Clone apps of existing app mining registrants will not be added to the program.

**Comment by dmailonline** [comment]
Can you give some examples to be more clear.

**Comment by GinaAbrams** [comment]
Sure. https://michaelbelisle.tk/ appears to be an exact clone (with the same website copy) as OI calendar.

**Comment by dmailonline** [comment]
Yes .. you are totally right

**Comment by friedger** [comment]
Just to clarify, I worked with Michael to build the calendar with his favorite colors. Users should have control over their UI. The source code of both apps is published under MIT license.

For reference, there was is a closed issue: #75 

The reference to Apple rules should also include stories where this rule prevents privacy/innovation: https://mobile.twitter.com/FranDepascuali/status/1132061850756091905

This rule is difficult to implement objectively, especially for close source app (see #11). 

I also understand that there is no benefit in reviewing an app if the app is similar to another app in the program. Probably, it should be stated that it is at the discretion of Blockstack PBC to identify an app as a clone (not having significant upgrades)

**Comment by GinaAbrams** [comment]
Thanks for the input, going to add this to the changelog and mark this as done: It is at the discretion of Blockstack PBC to identify an app as a clone (not having significant upgrades).
