### ISSUE TITLE
Reviewer: Can evaluate latest blockstack.js

### ISSUE THREAD

**Issue by jeffdomke** [blockstack/app-mining#12]

**Comment by jeffdomke** [comment]
@larrysalibra this sound useful or icebox?

**Comment by markmhx** [comment]
https://github.com/blockstack/blockstack-browser/issues/1902 will probably need to be released before reviewers can interrogate blockstack.js versions consistently for this issue

**Comment by larrysalibra** [comment]
I'm not sure what this issue is reviewing to. Is it asking if the app uses the latest blockstack.js?

**Comment by jeffdomke** [comment]
Spoke with Larry on this and we think it is better to evaluate the result of using our tech vs. the tech itself. Closing for now with no change.
