### ISSUE TITLE
Create a changelog for each audit period

### ISSUE THREAD

**Issue by hstove** [blockstack/app-mining#124]
This has already been discussed on the forum and in the app miner meeting, but it seems like we forgot to create an issue for it (from my quick check).

During the audit period, many people find corrections, like not using the right Product Hunt post for upvote data.

This change would implement a changelog during the audit period. Whenever a change is made, it would be logged in a "changelog". It might look like:

- _June 16_: App A had the wrong data from Product Hunt, since they reposted their app. We've collected the newer upvote data and updated the audit sheet.

**Comment by hstove** [comment]
Moving to "Done". This will be created with our audit results for July.

**Comment by hstove** [comment]
This is in-progress for this audit period, and is being updated :+1:

**Comment by GinaAbrams** [comment]
Added the link to the [audit changelog](https://docs.google.com/spreadsheets/d/1WrsyBdrqapZN-fv5VeD8SgU15CVnqAmnKVUHUMYiNkY/edit#gid=0) to the App Mining changelog. Closing.
