### ISSUE TITLE
Proposal: New App Reviewer - Simple Analytics

### ISSUE THREAD

**Issue by jehunter5811** [blockstack/app-mining#125]
**What is the problem you are seeing? Please describe.**

Tracking non-transaction-based decentralized app usage has been historically difficult. While page views is not perfect, it gives a glimpse into active use of an app. As it stands, App Mining does not have any active component to rating apps based on actual usage statistics. 

A partnership between SimpleAnalytics could make this possible and free to app devs who would otherwise reach for services that track users (like google analytics). 

**How is this problem misaligned with goals of app mining?**

By not focusing on usage as part of app mining, we are encouraging nothing more than flashy landing pages and marketing. While both are important, they mean nothing if they don’t translate to usage. SimpleAnalytics would help track usage. 

**What is the explicit recommendation you’re looking to propose?**

Based on the feedback from the community, the majority of people would not be opposed to SimpleAnalytics use. See Slack thread here:

https://blockstack.slack.com/archives/C074L9QQG/p1561673536170600

I recommend a partnership between Blockstack and SimpleAnalytics that would bring SA on as an app reviewer and would provide app devs with a free instance of SA. 

Each month (period defined by the app mining month), SA could provide a report of pages views for the app (not the app’s marketing site). App devs that do not want to participate should not be penalized, so this reviewer should only result in positive scores. 

**Describe your long term considerations in proposing this change. Please include the ways you can predict this recommendation could go wrong and possible ways mitigate.**

Not all devs will want to implement this. Therefore, it’s important to offer this as a possible score increased but not a score reducer. 

This plan relies on Blockstack working out a deal with SA to offer free plans to devs.

**Comment by friedger** [comment]
Would they deliver a number of active monthly users?

If you are not implementing the analytics, the reviewer would give an average score? I. e. Theta = 0? Does it discourage apps with users below average to not implement it?

**Comment by jehunter5811** [comment]
Yep, this is why I propose that this reviewer can only positively influence scores. So if you don’t think your usage is high enough, don’t implement it. But no matter what your usage is, you should always get a net positive score and that score. I don’t think this should be tracking month over month results, though that would be nice. But because of the problem you mentioned, it should start with just a score for the usage in a given month ranked against all other apps.

**Comment by cuevasm** [comment]
(We've talked with Fathom in the past about something like this!)

Biggest hurdle to me: How will you prevent gaming in a system like this? It's just as easy to buy website pageviews as it is Twitter followers. SA and Fathom are less adept at discounting bots because they just don't gather as much info to make their lists and don't have the years of machine learning in place that even Google Analytics does to weed out the obvious.

**Comment by jehunter5811** [comment]
That's a tough one to overcome, I admit. What would it look like if this code was implemented on the Blockstack Browser? Both the hosted and the locally downloaded version could track referal traffic, right? This would (maybe) limit the bot traffic since someone would have to actually click a log in button and be redirected to the browser?

**Comment by hstove** [comment]
We have been trying to figure out a way to track app usage, while remaining anonymous, while preventing gaming. It is quite hard to do all three. We have a few thoughts around how we could do this, but it ranges from making tradeoffs in one way or another.

We are working with some folks to figure out if there is a way to do this with zero-knowledge proofs, but it's still more of a research question 😬

The problem with doing it from the Blockstack Browser is that it only tracks logins, which is much less useful (I think) than daily active users.

**Comment by jeffdomke** [comment]
PBC team discussed again, we can't get over how this is more gameable than Awario. We've spoken with both Fathom and Simple and don't see a road forward here. Thx for suggesting. Moving to close this.
