### ISSUE TITLE
Publish App Mining Audit and Changes Criteria 

### ISSUE THREAD

**Issue by GinaAbrams** [blockstack/app-mining#126]

**Comment by jeffdomke** [comment]
Gina will draft something here.

**Comment by GinaAbrams** [comment]
With an extended audit period, app founders should have clear means of communication with the PBC team and reviewers to make necessary changes within the timeframe. Outside of the audit period, if an error is found, the error should be updated but no difference in payment will be made unless the error was egregious at the discretion of Blockstack PBC. This encourages app founders to thoroughly audit results during the audit period and can lead to transparent and consistent results on a monthly basis.

**Comment by jeffdomke** [comment]
Sounds like this is done just need to put in changelog.
