### ISSUE TITLE
Proposal: Do not payout apps with 0 reach on Awario

### ISSUE THREAD

**Issue by friedger** [blockstack/app-mining#127]
**What is the problem you are seeing? Please describe.**
App developers that do not care about their apps anymore are still paid out monthly rewards.

**How is this problem misaligned with goals of app mining?**
This discourages app developers that actively develop their apps.

**What is the explicit recommendation you’re looking to propose?**
* Add requirement to communicate about the app in the app mining rules, i.e. have a reach > 0 by Awario.
* Mark apps that have a reach of 0 on Awario as illegible.

**Describe your long term considerations in proposing this change. Please include the ways you can predict this recommendation could go wrong and possible ways mitigate.**
This is a general improvement over the current situation. It is easy to implement.

The additional requirement is an acceptable burden on app publishers even if they do not usual do marketing.

App developers that do not want to develop their apps anymore can still send a tweet or so once a month and thereby receive rewards. This is no different without this improvement. However, app developers that do not care at all won't get any rewards.

This rule needs to be reviewed if app reviewer Awario is removed.

**Additional context**
There was a general consent in  #64 that it is a good idea to exclude apps in rewards that are not developed anymore. However, a fair way was not found back then.

**Comment by cuevasm** [comment]
This could be interesting, do you think though, that social media activity is a fair indicator of active or inactive development? I think it could be a decent proxy for a lot of people, but also happen to know for a fact a few teams that are very quiet and still work on their app, but aren't worried about marketing at the moment. Would we want to make teams like that ineligible because they didn't generate any awareness?

**Comment by GinaAbrams** [comment]
> a few teams that are very quiet and still work on their app, but aren't worried about marketing at the moment.

*+1*

**Comment by Walterion1** [comment]
I should agree with @friedger as a month period seems good enough for any "very quiet" projects to talk about it at least one time. Otherwise an alternative will be monitoring the repository of source codes, and I think you will agree this way is not practical.
Without this activity pressure, someone can make and release an app one time and left it to be without any update and after some month, it cause some dissatisfied users and dead apps.

**Comment by friedger** [comment]
If a team is so busy that they can't tell the community that they are still alive then they should not be eligible.

I am happy to mention the product if I know what the team is doing. Please put me in contact with them.

It is not about marketing, but communication.

**Comment by cuevasm** [comment]
If it's not about marketing, then we shouldn't be using Awario to measure it, we should have some other mechanism. While I firmly believe all projects should be marketing on some level, I don't think it's a fair proxy for 'active development' or something that they should be removed for choosing not to do. Of course, I don't recommend it, and it should hurt them, but going as far as requiring it to the point of removal doesn't seem fair. 
 
Potentially a better proxy for this is to require that App Miners all fill in our quarterly survey. We could even add questions that ask them to recap what they've worked on. I think if you're trying to control for knowing if a team is 'alive' then we should just direct to them vs. measuring an output that's not necessarily coupled. If they can't fill out a short survey 4 times year, then I wholeheartedly agree that is a dead project and should be removed.

Other ideas that could solve this that I personally would support:
- Removing the bottom 10% of teams at a regular interval
- Removing teams that get zeroes with multiple App Reviewers
- Removing teams that show no progress with ANY App Reviewer over multiple months (and are not ranked in the top X%)
- Removal for extended unresponsiveness to PBC team by a survey of some sort

**Comment by friedger** [comment]
I though checking the awario reach for > 0 was easy to implement to measure some kind of liveliness. I am happy to see other means implemented:

> Removing the bottom 10% of teams at a regular interval
Hmm, could hit the wrong teams but as the last 10% only get tiny amounts it does not really matter. It would matter if we implement #80 and #25 .

>Removing teams that get zeroes with multiple App Reviewers
NIL and awario would be the only reviewers that the can give zeroes at the moment. Even product hunt has at least a 1.

>Removing teams that show no progress with ANY App Reviewer over multiple months (and are not ranked in the top X%)
I like that but some reviewer scores are a bit volatile, like PH.

>Removal for extended unresponsiveness to PBC team by a survey of some sort
Definitively, yes!

**Comment by friedger** [comment]
On app-center.openintents.org there is now a UI that allows app publishers to post monthly updates.

**Comment by jeffdomke** [comment]
PBC discussed and don't feel like this is aligned with our goals or process. Closing this.

**Comment by friedger** [comment]
@jeffdomke Could you elaborate on the misalignment?
