### ISSUE TITLE
Awario Growth suggest bi-monthly promotion period

### ISSUE THREAD

**Issue by friedger** [blockstack/app-mining#129]
**What is the problem you are seeing? Please describe.**
Timestack lost 100% of reach (58.000 to 0), resulting in a Growth Z of -0.16
Utilo gained 130.000% of reach (29 to 38.000), resulting in a Growth Z of 7.1

**How is this problem misaligned with goals of app mining?**
This score method suggests that it is good to promote the app only every other month. This is against the goal of growing the ecosystem.

**What is the explicit recommendation you’re looking to propose?**
Use LOG(reach(month -1) - reach(month))

**Comment by friedger** [comment]
Furthermore, a growth of 600% weighs nearly as much as a loss of 100% (-0.12 vs -0.16)

**Comment by jeffdomke** [comment]
Thanks @friedger PBC team discussed and we think this is a good change. It kind of depends on the larger decisions around how we use Awario scores (if at all). @cuevasm will follow up on this larger topic and revisit this shortly.

**Comment by GinaAbrams** [comment]
We will consider this after finalizing awario scoring method in #135. Moving to backlog until then.

**Comment by friedger** [comment]
The blended awareness still suggest this behaviour: For example in November (audit data)
* one app gained reach + 20k (2,500 to 23,000) resulting in Growth Z of 3,4
* another app lost reach - 400k (420,000 to 1,200) resulting in Growth Z of -0.4

**Comment by cuevasm** [comment]
My only hesitation with this is introducing a further delay in getting a full Awario score. @hstove can you check this math and let me know if there are other ways of solving what Friedger is raising please?

**Comment by cuevasm** [comment]
Going to continue this discussion on #204 which is a stronger proposal for solving the same issue.
