### ISSUE TITLE
Proposal: Active state reviewer

### ISSUE THREAD

**Issue by friedger** [blockstack/app-mining#132]
**What is the problem you are seeing? Please describe.**
Some teams stop developing, promoting, maintaining their apps.

**How is this problem misaligned with goals of app mining?**
It is unfair to other teams that do improve their apps.

**What is the explicit recommendation you’re looking to propose?**
Add a reviewer that provides proof of activity for each team publicly,
e.g. marketing activity, development activity, design activity.

The reviewer gives a score of 1 if the team is active otherwise -1. If the reviewer can't get any information from the team, then the reviewer will mark the app as ineligible.

**Describe your long term considerations in proposing this change. Please include the ways you can predict this recommendation could go wrong and possible ways mitigate.**
This can be automated process that is supervised by a DAO in the future

**Additional context**
#64

**Comment by Arrakis8** [comment]
> 
> 
> **What is the problem you are seeing? Please describe.**
> Some teams stop developing, promoting, maintaining their apps.
> 
> **How is this problem misaligned with goals of app mining?**
> It is unfair to other teams that do improve their apps.
> 
> **What is the explicit recommendation you’re looking to propose?**
> Add a reviewer that provides proof of activity for each team publicly,
> e.g. marketing activity, development activity, design activity.
> 
> The reviewer gives a score of 1 if the team is active otherwise -1. If the reviewer can't get any information from the team, then the reviewer will mark the app as ineligible.
> 
> **Describe your long term considerations in proposing this change. Please include the ways you can predict this recommendation could go wrong and possible ways mitigate.**
> This can be automated process that is supervised by a DAO in the future
> 
> **Additional context**
> #64

My Equipool miner is not working correctly. How do I get it to work? It mines and the miner shows speed as 21 sols/s, BUT when I go to the Equipool data site it shows Speed 0, and Avg speed 0. Why is this app not working? Red letters on my miner say "INFO: GPU0 Rejected share 50ms [A: 0, R:1 (or R:2 or R:3 etc)]. I got screenshots.

**Comment by jeffdomke** [comment]
This is a cool idea. PBC can't do this so would need an external party we trust. Who would do this. I also think we would not want to remove apps at this time, but we would like to reward those who improve their app vs. those who make not progress.

**Comment by friedger** [comment]
What would be the requirements? OpenIntents could provide such reviews.

**Comment by friedger** [comment]
A score for different activity levels could be possible as well.

**Comment by friedger** [comment]
Continued in #138
