### ISSUE TITLE
Re Stealthy: TryMyUI: Can we add any specific instructions in there for the end-users? 

### ISSUE THREAD

**Issue by jeffdomke** [blockstack/app-mining#14]

**Comment by jeffdomke** [comment]
We discussed and worried apps giving themselves preferential instructions that could mess with rankings. This can devolve into a game of who can write instructions that hide your apps down-sides the best.

**Comment by AC-FTW** [comment]
It seems like TryMyUI has the infrastructure for this and the problem is somewhat related to issue #52 #

**Comment by GinaAbrams** [comment]
I think this is an old issue and has been addressed in #1. Closing, but if it needs to be reopened please do so.
