### ISSUE TITLE
App Reviewers can't deem apps ineligible

### ISSUE THREAD

**Issue by xanbots** [blockstack/app-mining#140]
**What is the problem you are seeing? Please describe.**
Every month some number of apps that have been deemed eligible by Blockstack PBC, and put in "Ready" status on App.co/mining/apps, are subsequently deemed ineligible during the ranking period by one or more app reviewers. Last month this happened to 10-15 apps. This typically happens because of a bug or setup used by a reviewer where they can't authenticate. 

**How is this problem misaligned with goals of app mining?**
App creators and Blockstack PBC don't have clarity of whether or not an app is eligible until after App Reviewers have submitted their rankings. Apps should have a binary understanding of App Mining eligibility at the beginning of each month. If bugs exist in apps, or individual reviewers are unable to assess certain apps, those should be ranked towards the bottom vs. not being eligible. 

**What is the explicit recommendation you’re looking to propose?**
If apps meet all requirements for eligibility, and are deemed eligible by Blockstack PBC at the beginning of an App Mining run, they are eligible for that run. Any App Reviewer who discovers bugs or issues with judging an app will give it a score reflecting this fact, and the ranking will therefore be very low.

**Comment by friedger** [comment]
Will Blockstack PBC review all apps each month for eligibility?

**Comment by xanbots** [comment]
We already do this, and is reflected on the app.co/mining/apps page with each app's status as either "Ready" or "Not Ready".

**Comment by friedger** [comment]
Isn't it unfair to payout rewards to app publishers that do not care, that do not fix their bugs, .. ?

**Comment by GinaAbrams** [comment]
@friedger I don't think this is what that ticket is arguing for. Please start a new ticket for that topic.

PBC discussed and feel it is better to set expectations for newly enrolling app miners instead of changing the current process. Next steps: update docs. I will follow up with copy.

**Comment by friedger** [comment]
My point was that reviewers should be able to flag apps as ineligible when
they can review the app. With this proposal the flagged apps could become
ineligible for next month if Blockstack PBC thinks so with the information
provided by the reviewers

**Comment by friedger** [comment]
@GinaAbrams Is the proposal accepted or rejected?
