### ISSUE TITLE
NIL: Clarification alternative DID auth method

### ISSUE THREAD

**Issue by friedger** [blockstack/app-mining#145]
How is the use of alternative DID auth methods counts in NIL auth score?

For example in https://chat.openintents.org/#/login
![Screenshot from 2019-09-02 23-10-43](https://user-images.githubusercontent.com/1449049/64157490-17d6ff80-ce37-11e9-8d4c-a6dc22ac44b3.png)

**Comment by larrysalibra** [comment]
Anything that's not Blockstack auth is treated as a 3rd party login method.
