### ISSUE TITLE
Add more support for native apps

### ISSUE THREAD

**Issue by Walterion1** [blockstack/app-mining#156]
**What is the problem you are seeing? Please describe.**
There should be a consideration of finding issues of apps not made on top of  Blockstack.js if the reviewer diagnosis that it is not an obvious bug because of the absence of care.

**How is this problem misaligned with goals of app mining?**
If we want to have native apps made integrated with Blockstack, we should help them grow and give them a little more attention, as for now there is no official SDK and support for them.
It helps to bring more awareness to Desktop users and integration of Blockstack Auth to them, welcoming new developers and users to the community.

**What is the explicit recommendation you're looking to propose?**
If a reviewer (e.g., NIL) finds an issue, it can share them with the developers at the time. As the count is very low, it can not be a big task to do.
**Update:** Or have any other support to help this way of making apps for Windows, macOS, and Linux.

**Describe your long term considerations in proposing this change. Please include the ways you can predict this recommendation could go wrong, and possible ways mitigate.**

There are official SDKs for Web, Android, iOS made by Blockstack and specified development team.
It can be done until there are more developers focused on native apps and normally more stability in the toolkit and SDK, or there is an official SDK from Blockstack with the PBC support.

**Additional context**

We are passionate about Desktop just as Web. There was not ready toolkit to make native Desktop apps and give pure experience integrated with Blockstack Auth.
It made us do it by our self, we port Blockstack.js, and it is shared [here](https://github.com/blackholeorganization/BlockstackPascal). We built some apps on top of it, and they went well like BlackHole and now it is in the top most-used apps.
This month, three native apps were removed form mining because of one bug only happened on the NIL reviewer machine. Now NIL kindly shared the issue and helped to fix the problem, but it was late and led to very unfortunate removal.
This one little bug leads to the removal of months of work. One was Marks one of the Winners of CBE2 and One Dadroit the 4th of last month. If there were more support like other platforms, such problems would not happen. So it would be nice to give them a little slack until these can grow and no need for extra care.

**Comment by friedger** [comment]
I understand that the reviewer shared the issue with you already. So, the issue could be closed, couldn't it?

Do you want to establish a process where each reviewers provides individual feedback?

**Comment by Walterion1** [comment]
I think I made my point clear that if we like to have native apps that have no official SDK or Lib, we can have a more collaborative way to help them grow.
Such bugs are not because of absence of care from developers (eg when a JS app has a corrupted login as the lib is stable) and they are because of the SDK being young and need more support.

I like to know more opinion about this, and this issue is meant to know that.

**Comment by jeffdomke** [comment]
@larrysalibra any opinions here on how this would impact testing? Or how this conflicts with your current test plan? Thx.

**Comment by dantrevino** [comment]
Can we define support?

**Comment by jeffdomke** [comment]
@larrysalibra please weigh in here. Moving to review.

**Comment by larrysalibra** [comment]
The problem with native apps is that we don't have much insight into what they are doing because we don't control the operating system and it generally isn't easy or possible (ios) for us to put software between native apps and the rest of the internet to audit what they are doing or enforce a set of rules against them. 

For these reasons, I would tend to take the opposite viewpoint and suggest that we consider excluding native apps both desktop and mobile until which time we have adequate means to enforce a set of "can't be evil" rules against them on behalf of users.

**Comment by njordhov** [comment]
NIL is 50% of the score for debuting apps, but only 25% of the score for incumbents. This creates a dynamics that should be taken into account when changing the weight of NIL.
