### ISSUE TITLE
Use issues here for error reports during audit period

### ISSUE THREAD

**Issue by friedger** [blockstack/app-mining#159]
**What is the problem you are seeing? Please describe.**
Error reports during the audit period are not transparent. Error reports are mainly reported by developers that inspect their own app scores.

**How is this problem misaligned with goals of app mining?**
Error reports should detect errors in the algorithms and human errors that apply to all apps in the same way.

**What is the explicit recommendation you’re looking to propose?**
Add a template for error reports and only accept error report through github issues.

**Describe your long term considerations in proposing this change. Please include the ways you can predict this recommendation could go wrong and possible ways mitigate.**
Error reports reported as issues can be used to clarify weaknesses in the process.

**Additional context**
An app was retested through TMUI with a different audience setting after the testing period. Other developers voiced concerns that this retest should not be accepted as an error report.

**Comment by ViniciusBP** [comment]
100% support for this. About the retest, it was even worse than changing audience, he developed almost everything during the middle of the  month.  

We need clear rules on retests.

**Comment by GinaAbrams** [comment]
We have updated the app mining audit period criteria, and people are no longer able to have their apps re-tested based on audience preferences. Operationally, it's best to have an email record of requests for the audit period as information can't be edited. Going to close this for now and let us know if we should re-open.
