### ISSUE TITLE
Re Stealthy: TryMyUI: Can we ensure we get testing from both iOS and Android users?

### ISSUE THREAD

**Issue by jeffdomke** [blockstack/app-mining#16]

**Comment by jeffdomke** [comment]
Short term fix: 4 and 4.

**Comment by hstove** [comment]
Let's add a section to the docs/README to make this known in relation to the TryMyUI testing instructions.

**Comment by GinaAbrams** [comment]
Closing in lieu of #134 in [docs repo](https://github.com/blockstack/docs.blockstack/issues/134)
