### ISSUE TITLE
App Mining Payout Tax Implications

### ISSUE THREAD

**Issue by kkomaz** [blockstack/app-mining#160]
**What is the problem you are seeing? Please describe.**
After the October App Mining payouts, payouts will be done 100% in the form of STX tokens.  This is a problem for both US and non US citizens because tokens will be taxed as income but cannot be converted to liquid form.

Specifically for US citizens, I saw a response from Muneeb on CNBC regarding the token's liquidity mentioned here https://youtu.be/-GTmOHrUJzw?t=279.  Based on the clip, It seems like priority will be given to the asian markets where US citizens will not be allowed to trade.  He also mentions in a tweet that this issue is a short-term and temporary but without any real timeline.  This will put a lot of pressure and burden on app developers to not only invest their time developing but also pay taxes on an income that can not be liquidated.

**How is this problem misaligned with goals of app mining?**
App mining is an incentive program for developers to learn the blockstack ecosystem and bootstrap a project.  With the financial support, developers should be able to use the funds to promote their product, hire contractors, marketing, etc.  However, this can not be done without having liquidity in the STX token.

**What is the explicit recommendation you’re looking to propose?**
One of two options

1. Continue bitcoin payments to developers until liquidity of STX tokens are confirmed.  
2. Receive partial BTC payments that offset the tax liability received in STX token.

**Describe your long term considerations in proposing this change. Please include the ways you can predict this recommendation could go wrong and possible ways mitigate.**
The proposals above will put less burden on the developers to pay for taxes on an illiquid asset.  Keep in mind that receiving STX as income is very different than investing.  Developers should be given the opportunity to sell their STX or some transparency is needed when/how it would be possible to liquidize.

**Comment by pstan26** [comment]
Yea that’s a good point Alex. There’s also a lot of folks entering. Been thinking, for major tax reasons maybe it makes sense to continue or even increase BTC payouts and even push out STX payments once there is liquidity?

**Comment by dantrevino** [comment]
@pstan26 another question wrt STX payouts, what market(s) will you use as an index to determine STX value?  If there are no US markets, but a hypothetical Korean market is trading at $0.15, would you double up the STX to account for dollar value promised in app minng?

**Comment by GinaAbrams** [comment]
November marks the planned switch of App Mining payouts in BTC, to Stacks. Until there is an official liquidity option for the community, there’s room to help folks via continuing paying in BTC and adjusting the STX payout to potentially offset taxes for those who are participating in App Mining. The proposals below may offset potential tax consequences for the $500k in STX payouts and $0 in Bitcoin, and can be implemented as soon as November. 

Below we’ve outlined two proposals for feedback to see which one of the options are preferred. We can revert back to this issue once there are more liquidity options to update the schedule again. 


**Proposal A:** 

STX payout pool: 300k and 5% distribution curve 
BTC payout pool: 100k and 5% distribution curve 

Additional BTC payments to potentially cover taxes on STX earnings for the time being. 

![Earnings Across Top 20 Teams, Proposal A](https://paper-attachments.dropbox.com/s_E8D605DD4DF0CCCECAC63EB003C80CFDF18E0D9C1899466A5E44D5BBE094ACA8_1570654155281_Screen+Shot+2019-10-09+at+4.48.12+PM.png)

![Payout Distribution Curve for Proposal A](https://paper-attachments.dropbox.com/s_E8D605DD4DF0CCCECAC63EB003C80CFDF18E0D9C1899466A5E44D5BBE094ACA8_1570213961191_file.png)

**Proposal B**

STX payout pool: 200k and 5% distribution curve 
BTC payout pool: 100k and 5% distribution curve 

Slightly more earnings after taxable income,  but less payouts overall.  

![Earnings Across Top 20 Teams, Proposal B](https://paper-attachments.dropbox.com/s_E8D605DD4DF0CCCECAC63EB003C80CFDF18E0D9C1899466A5E44D5BBE094ACA8_1570654306468_Screen+Shot+2019-10-09+at+4.50.43+PM.png)



![Payout Distribution Curve for Proposal B](https://paper-attachments.dropbox.com/s_E8D605DD4DF0CCCECAC63EB003C80CFDF18E0D9C1899466A5E44D5BBE094ACA8_1570214457216_file.png)


**Between proposal A or B, what is the preference from the App Mining community?**   

**Important Disclaimer**
The Securities and Exchange Commission (SEC) has qualified the offering statement that we have filed with the SEC. The information in that offering statement is more complete than the information we are providing now, and could differ in important ways. You must read the documents filed with the SEC before investing. The offering is being made only by means of its offering statement. This document shall not constitute an offer to sell or the solicitation of an offer to buy, nor shall there be any sale of these securities in any state or jurisdiction in which such offer, solicitation or sale would be unlawful prior to registration or qualification under the securities laws of any such state or jurisdiction.

An indication of interest involves no obligation or commitment of any kind. Any person interested in investing in any offering of Stacks Tokens should review our disclosures and the publicly filed offering statement and the final offering circular that is part of that offering statement here. Blockstack is not registered, licensed or supervised as a broker dealer or investment adviser by the SEC, the Financial Industry Regulatory Authority (FINRA) or any other financial regulatory authority or licensed to provide any financial advice or services.

**No Tax Advice**
We are not making any warranties or representations to you with respect to the tax consequences associated with your holdings of STX tokens. You are hereby advised to consult with your own tax advisor with respect to any tax consequences associated with the STX token.

**Comment by friedger** [comment]
Proposal A

**Comment by vishnuraghunathan** [comment]
Why is the payout reduced from a total of $500,000? It significantly reduces the total payouts for founders based outside of US. Also, you mentioned that proposal B ensures higher earnings after taxable income. Can you explain the calculation?

**Comment by GinaAbrams** [comment]
The numbers above are a new version that take into account 3 months of additional BTC payouts, and that STX has yet to gain liquidity. With higher STX payouts comes higher potential tax burden, which is why we proposed to update the payouts until there are better liquidity options. 

In proposal B, calculating a rate of roughly 30% taxes, the BTC amount can potentially help to cover a larger portion of the tax burden for app miners. 

Realize the description there was confusing, thank you for the question @vishnuraghunathan  !

**Comment by vishnuraghunathan** [comment]
Thanks for your response @GinaAbrams .  I was a bit confused about earnings part.. But now i did the math and understood what you were pointing at. I have two questions. 

Why cannot the total payout remain unaltered?  Is there a particular reason why we have not opted for a breakup of 350 STX + 150 BTC or 400 STX + 100 BTC??  

and the second question is instead of having to choose between 300 STX + 100 BTC and 200 STX + 100 BTC, we can opt for 250 STX + 150 BTC which in my understanding addresses both total payouts as well as net earnings.

**Comment by vishnuraghunathan** [comment]
Thanks @GinaAbrams . i go with Proposal A

**Comment by kkomaz** [comment]
Proposal B

**Comment by kkomaz** [comment]
@GinaAbrams 

Just to confirm every payment in $STX will be at $0.30?  I see on Binance (approved exchange outside of US) at $0.21.  

Is it possible to get paid at fair market price similar to that of bitcoin payments?

**Comment by GinaAbrams** [comment]
Hey @kkomaz this is what is in our circular: 

The price of the Stacks Tokens distributed under the App Mining program in exchange for non-cash consideration will be deemed to be $0.30 per token for at least three months from the first distribution [`note: this is the Hard Fork Date in October, when tokens were first distributed`] of tokens pursuant to this offering circular, for purposes of determining whether over $40,000,000 of Stacks Tokens have been sold under this offering.  If at any time following that three-month period the Stacks Tokens are traded on one or more authorized exchanges or alternative trading systems, and there are trades for at least one million Stacks Tokens executed through or on exchanges or alternative trading systems during any calendar month (any such month, a “calculation month”), then we will value the tokens paid to developers in the following month and in all subsequent months until and including the end of the next calculation month at the average closing bid price for the tokens during the calculation month.  We will disclose both any changes to the price of the Stacks Tokens to be distributed pursuant to this offering circular, and whether the new calculation price will result in a curtailment of the number of Stacks Tokens being issued in the next month, using either an offering circular supplement filed under Rule 253(g)(2) or a post-qualification amendment, depending on the facts and circumstances at the time of such change.
