### ISSUE TITLE
[Docs] Add NIL policies

### ISSUE THREAD

**Issue by friedger** [blockstack/app-mining#162]
As an app reviewer, I would like to learn how NIL is working. Currently, there are several places that provide this information. It is unclear what is the "source of truth".

Link from readme:
https://blog.blockstack.org/introducing-new-internet-labs-the-digital-rights-reviewer-for-app-mining/

Link from docs about app mining:
https://docs.blockstack.org/develop/app-reviewers.html

Description in forum:
https://forum.blockstack.org/t/august-2019-app-mining-nil-proposals-and-policy-clarifications/8943

**Comment by larrysalibra** [comment]
This is great idea. I'll send a pull request to this repo with a doc.

**Comment by larrysalibra** [comment]
Here's a draft: https://github.com/newinternetlabs/app-mining/blob/master/nil.md

**Comment by friedger** [comment]
@larrysalibra This doc should go to docs.blockstack.org

as discussed in https://github.com/blockstack/app-mining/issues/89

**Comment by larrysalibra** [comment]
Thanks for the heads up about this @friedger - I’ll migrate it at some future date.
