### ISSUE TITLE
Review TryMyUI videos for testing errors: Lio

### ISSUE THREAD

**Issue by jeffdomke** [blockstack/app-mining#17]

**Comment by jeffdomke** [comment]
Gina needs to share the error with the team.

**Comment by hstove** [comment]
Tim looked at the Lio videos, and there was a similar situation to XOR where the users were heading to Blockstack websites. There was a bug in Lio where, when they finish onboarding, the button says 'go to Blockstack' when it should say 'go to Lio'. Possible fix is to upgrade blockstack.js to latest.

**Comment by GinaAbrams** [comment]
Emailed them, so closing.
