### ISSUE TITLE
Blockstack Browser does not sign-in users with apps using collections

### ISSUE THREAD

**Issue by friedger** [blockstack/app-mining#172]
The current Blockstack Browser version does not handle auth requests gracefully: https://github.com/blockstack/blockstack-browser/issues/1892#issuecomment-552079442

Affected apps: Gitix, Webby

How should the app mining reviewers handle this?

There was an issue like this in the past: #112

**Comment by jeffdomke** [comment]
@friedger i understand the problem and agree we should fix this in the browser. Is there an App Mining policy change you are proposing? If not, I'm inclined to close and deal with this problem over in the browser repo.

**Comment by friedger** [comment]
@jeffdomke For me, it is not clear from the app mining rules how these case(s) should be handled if the bug effects the app mining results. I don't have an insight whether it has any effect at all. I just wanted to make the issue public.

**Comment by jeffdomke** [comment]
Chatting with Hank on this, it sounds like we are releasing a fix in the browser this week. Assume that will take care of this. Moving to done.

**Comment by friedger** [comment]
@jeffdomke OI Timesheet was affected by this bug and removed from app mining. Is it just bad luck?

**Comment by friedger** [comment]
Apparently, it was just bad luck. 
The Blockstack Browser will be fixed...
