### ISSUE TITLE
Mobile-only apps on-boarding problem

### ISSUE THREAD

**Issue by hammadtq** [blockstack/app-mining#180]
**What is the problem you are seeing? Please describe.**

If you look at the [app submission page](https://app.co/submit), there is no place to provide a URL for your iOS and/or Android app. Mobile app devs usually start from a single platform and they usually don't have a website. In other cases, websites can be complex, such as if you land on Yahoo's main page, you will have trouble finding their app download button while you will see several other services that can be centralized and a reviewer can try to Sign-in in to one of those services (having no information that they are looking for an app).

Similarly, on the front-end, "Get Dapp" button on app information page just takes you to the website and user is left with the task of finding the mobile-app.

**How is this problem misaligned with goals of app mining?**
Mobile-only app developers are not included in the process. The submission process and the front-end website is optimized for web-only apps.

 *What is the explicit recommendation you’re looking to propose?**
Add URL text input types for mobile-apps namely for Apple Appstore and Android Play store, can be generic as developer might have their app on an alternative Android store.

**Describe your long term considerations in proposing this change. Please include the ways you can predict this recommendation could go wrong and possible ways mitigate.**
This is a process oriented problem where data is not being collected properly. It does have implications on scale such as reviewers will keep on getting confused which app they need to review and app devs will keep on becoming frustrated.

**Additional context**
This has happened with me when I submitted Vegan Scanner - Is it Vegan? app. The website is veganscanner.me, where there was a default Sign-In button from Hello, Blockstack web-app example that comes with the SDK. The domain name and website was just used to get the auth working on the iOS app. Once prompted during the submission process, I gave the same URL in the website box and probably stuffed the actual app store URL somewhere else. The NIL reviewer tried signing-in by using the same button on the website and declared the app un-usable while he/she/they never saw the actual iOS app that was submitted for the review.

**Comment by jeffdomke** [comment]
Issue moved to [blockstack/app.co #708](https://github.com/blockstack/app.co/issues/708) via [**ZenHub**](https://www.zenhub.com/)
