### ISSUE TITLE
[Meta] Better structured proposal process

### ISSUE THREAD

**Issue by friedger** [blockstack/app-mining#194]
**What is the problem you are seeing? Please describe.**
During the last app miner call, some proposals were discussed and presented. The outcome of the call was unclear with regards to the status of the proposals. Attendees were invited to further comment on github.

**What is the explicit recommendation you’re looking to propose?**
Adopt "consent decision making" better!
Github issue should be distinguished between "proposals" and "agreements".

Proposals are github issues that are still open for opinions
Agreements are proposals that are considered good enough for now and safe enough to try until the next review.

During the app miner calls present the github issues in these two categories.

**Describe your long term considerations in proposing this change. Please include the ways you can predict this recommendation could go wrong and possible ways mitigate.**
The app miner calls become more effective.

**Additional context**
During the November call for example Awario meetup change and sponsored articles change were discussed in the same way. While there were no objections to the meetup change, the sponsored articles change was a clear proposal (that was scraped)

**Comment by jeffdomke** [comment]
OK sure, we can try this at the call. Proposals and Agreements. cc @GinaAbrams
