### ISSUE TITLE
Ignore youtube videos from awario count that do not show app information

### ISSUE THREAD

**Issue by friedger** [blockstack/app-mining#210]
**What is the problem you are seeing? Please describe.**
Awario only looks at the title and description of youtube videos, not on the video itself. Some videos that contain app names in the description do not contain any information about the apps in the video.

**How is this problem misaligned with goals of app mining?**
The purpose of awario social score is to encourage meaningful interaction on the social networks. Youtube videos without any information about the app should not count towards the social score for youtube.

**What is the explicit recommendation you’re looking to propose?**
1. Add documentation that youtube videos must contain information about the app.
2. Ignore youtube videos from awario social score if they are flagged during auditing period as non-app releated.

**What is the dry run period (if any)**
No dry run period. Apply this with the next app mining period.

**Describe your long term considerations in proposing this change. Please include the ways you can predict this recommendation could go wrong and possible ways mitigate.**
This could be applied to instagram as well.

**Additional context**
Example: https://www.youtube.com/watch?v=aLb-XvYtFOc The video itself does not contain any information about the apps that are mentioned in the description.

**Comment by cuevasm** [comment]
This is a very misleading title, so I suggest you update that. The post you've shared **absolutely** contains a reference to the apps as they are instructed to, using the caption area. This is how Awario detects Mentions on YouTube for everyone. What you are suggesting is a change as to how YouTube videos are counted, not that this post didn't mention apps, as of course it did.

I believe that if YouTube's own algorithms and team have no issue with a video, we should not get into further policing it. 1) it's extremely time-consuming to go watch videos as this ultimately would require and 2) everyone will have a vastly different idea of what qualifies. Sticking to the exact rules here makes the most sense to me. If someone wants to damage their brand like this, then they are free to do so, but as far as the rules currently stand, they met the qualification for an Awario mention.

**Comment by friedger** [comment]
I have updated the title. This issue is not about the content of the description but about the content of the video.

I think we should get into policing if we want Blockstack App Mining to become a meaningful tool for the ecosystem. At least we should raise the standard for the requirements. Rewarding brands for app-irrelevant videos damages the App Mining program.

In the long run, this issue does not matter because all apps will have many meaningful youtube videos per months. Until then, we should give auditors tools to raise the standards.

**Comment by cuevasm** [comment]
1) Auditors are inherently biased
2) Auditors have radically different ideas about standards
3) This makes someone the decision-maker on reported content. Even with relatively clear 'standards', it's going to be a subjective decision. Who does this? Is there an appeals process? 

If you can solve even one of those, then I think this conversation could move forward productively.

I would still ask: Is solving this really moving the needle? Is this such a pervasive problem that it is worth the community's time in tackling at this time?

**Comment by njordhov** [comment]
A video may not mention the actual app yet be part of a reasonable marketing campaign. For example, a video promoting OI App Center could review other Blockstack apps to draw in viewers, while only mentioning OI App Center in the text.

Perhaps the concern here is that some may get awario point for youtube without making much of an effort?

**Comment by friedger** [comment]
I would argue that then the video should be accounted for the other Blockstack app.

Measuring effort for the first video each month is probably not worth it. Closing this issue.
