### ISSUE TITLE
Make explicit that timeframes are in GMT

### ISSUE THREAD

**Issue by njordhov** [blockstack/app-mining#211]
**What is the problem you are seeing? Please describe.**

It is not clear what timezone is used for start and end of months, which matters for Awario scoring.

**How is this problem misaligned with goals of app mining?**

It can be confusing and lead to unhappy participants that get less scores on technicalities.

**What is the explicit recommendation you’re looking to propose?**

Clearly state that GMT timezone applies, perhaps even with a link to timezone conversion.

**What is the dry run period (if any)**

None. @cuevasm has already committed to implement it in private communication so this is just for the record.

**Describe your long term considerations in proposing this change. Please include the ways you can predict this recommendation could go wrong and possible ways mitigate.**

N/A

**Additional context**

**Comment by cuevasm** [comment]
Thanks, the only action here is to update the docs and I've already created an issue in our docs repo.
