### ISSUE TITLE
New internet labs proposal dry run

### ISSUE THREAD

**Issue by uonuon** [blockstack/app-mining#215]
1 - **App Redirection**: I saw the dry run last month and found out that Dmails No Redirect score is 0, meanwhile the app has no redirection, i wonder if New internet labs identify the landing page as a part of the app or not, for example dmail's Links:
**Landing page**: https://dmail.online/
**App**: https://app.dmail.online/ 
The user can only authenticate through the app, i wonder how can i reproduce the issue of redirection, since i tried the NIL Extensions and i found that Preventing Evil and Reporting Evil are active.

2 - **The Third Parties**: I am also having a problem with third parties it always gets red using the blockstack gaia, for example here in dmail i am trying to get users images from the gaia and it always gets red! 

![image](https://user-images.githubusercontent.com/15096591/71667538-39f17780-2d6e-11ea-96fa-47944598eca8.png)

3 - **Cookies**: Somehow when getting another users images from user's gaia blockstack sets a cookies into the app how to prevent that?

![image](https://user-images.githubusercontent.com/15096591/71667757-1aa71a00-2d6f-11ea-98e4-17d561d4d267.png)

4 - I need to know what are preventing evil and reporting evil flags refers to? 
@larrysalibra

**Comment by sdsantos** [comment]
This questions might fit better the extension github repo: https://github.com/newinternetlabs/new-internet-extension/issues 
The images issue has been address already there, for example.

**Comment by uonuon** [comment]
@sdsantos Thanks i've added the issue there!
https://github.com/newinternetlabs/new-internet-extension/issues/9
