### ISSUE TITLE
Paying out STX to App Miners at fair market price from January 2020

### ISSUE THREAD

**Issue by praveenrkp** [blockstack/app-mining#220]
**What is the problem you are seeing? Please describe.**
The Stack tokens (STX) given to app miners every month as part of app mining payout is given at 1STX=$0.3. However, currently the rate at which Stacks is traded on Binance exchange is 1STX=$0.0937. In effect, app miners are getting 70% less than what has been communicated which is creating a huge disincentive for app miners. 

**What is the explicit recommendation you’re looking to propose?**
It would be in the interest of app miners and app mining community to offer App mining payouts for the month of January 2020 based on fair market price similar to that of bitcoin payments. Also, it was also mentioned somewhere here in a github post that app mining payout will be given at avg market rates. Would request other app miners to share the link here if possible.

**Comment by GinaAbrams** [comment]
February marks the first month following the 3-month time period after the first distribution of tokens pursuant to the offering circular, where the value of tokens will reflect the previous calendar month's closing bid price. 

From the [offering circular](https://stackstoken.com/static/offering-circular-20190711.pdf): The price of the Stacks Tokens distributed under the App Mining program in exchange for non-cash consideration will be deemed to be $0.30 per token for at least three months from the first distribution of tokens pursuant to this offering circular, for purposes of determining whether over 40,000,000 of Stacks Tokens have been sold under this offering. If at any time following that three-month period the Stacks Tokens are traded on one or more authorized exchanges or alternative trading systems, and there are trades for at least one million Stacks Tokens executed through or on exchanges or alternative trading systems during any calendar month (any such month, a “calculation* month”), then we will value the tokens paid to developers in the following month and in all subsequent months until and including the end of the next calculation month at the average closing bid price for the tokens during the calculation month. We will disclose both any changes to the price of the Stacks Tokens to be distributed pursuant to this offering circular, and whether the new calculation price will result in a curtailment of the number of Stacks Tokens being issued in the next month, using either an offering circular supplement filed under Rule 253(g)(2) or a post-qualification amendment, depending on the facts and circumstances at the time of such change.

**Comment by praveenrkp** [comment]
Cool. Thanks for the info @GinaAbrams

**Comment by praveenrkp** [comment]
Hi @GinaAbrams , as discussed in the thread earlier, the payouts for app mining in the month of February are to happen based on market rates of stacks in the previous month.  Just curious to know if the rate has been decided for this month?? If Yes, can you please share the calculation.

**Comment by GinaAbrams** [comment]
hey @praveenrkp the STX token price for February payouts will be $0.10. This was calculated by averaging the daily closing price from Jan 1 2020 to Jan 31 2020 (.09678584) and rounding.
