### ISSUE TITLE
Deadline timing is confusing: Update FAQ and docs

### ISSUE THREAD

**Issue by jeffdomke** [blockstack/app-mining#23]

**Comment by hstove** [comment]
A simple action item would be an FAQ item that includes the exact deadline guidelines (i.e. midnight the night before the first).

The countdown could also include the exact date. It could also have better language about what exactly is required (your app must be 'mining ready').

**Comment by hstove** [comment]
Issue moved to [blockstack/app.co #455](https://github.com/blockstack/app.co/issues/455) via [**ZenHub**](https://www.zenhub.com/)
