### ISSUE TITLE
February App mining Payouts 

### ISSUE THREAD

**Issue by praveenrkp** [blockstack/app-mining#235]
@GinaAbrams  Does this month app mining period adhere to payout pool mentioned in https://blog.blockstack.org/app-mining-plans-to-pay-blockstack-developers-1000000-in-stx-per-month/? (so would be 700000$ worth of STX tokens for payout). Thanks

**Comment by GinaAbrams** [comment]
The payouts are $500,000 total pool per the [docs](https://docs.blockstack.org/develop/mining-rewards.html#how-payouts-are-administered).
