### ISSUE TITLE
Product Hunt to add feedback to reviews 

### ISSUE THREAD

**Issue by GinaAbrams** [blockstack/app-mining#3]

**Comment by jeffdomke** [comment]
Need more clarity from PH.

**Comment by hstove** [comment]
@GinaAbrams to follow up again.

**Comment by AC-FTW** [comment]
This is still a significant problem in the February App Mining--specifically the Product Hunt Team score which is simply a number. I've outlined the problem further in my forum post (https://forum.blockstack.org/t/blockstack-february-app-mining-progress-review/7552/1):

> Issue #3:  ... [ @pstan26 ] ... mentioned in the January App Mining review that Blockstack has been talking with Product Hunt to get more information than just a number for the Product Hunt (PH) Team Score. The February data contained only a number. The Stealthy PH Team Score dropped from 8.85 in December to 6.25 in January and has remained there. Why? This is confusing. Stealthy underwent considerable UI and performance changes from January to February, which are reflected by Try My UI scoring (-.904 to .493). If the PH Team Score is about the product, why didn’t it reflect this? We believe the PH Team Score should be removed from App Mining until PH provides a detailed explanation about what influences it (note that we have no objection to continuing to use the Product Hunt Community Score in App Mining–though it’s game-ability is a separate issue to consider).

**Comment by GinaAbrams** [comment]
No longer relevant, closing. More info [here](https://forum.blockstack.org/t/march-2019-app-mining-results/7685/2)
