### ISSUE TITLE
Adjusting timing of ranking, payout, and announcement schedules

### ISSUE THREAD

**Issue by jeffdomke** [blockstack/app-mining#31]
Ongoing discussion on adjusting to improve accuracy and creating some buffer against errors. Relates to announcement schedules and timing. 

@hstove @GinaAbrams @cuevasm @pstan26 please contribute more thoughts.

**Comment by jeffdomke** [comment]
@GinaAbrams is leading this and the doc is currently in progress

**Comment by GinaAbrams** [comment]
Updated the [FAQ](https://app.co/mining#what-is-the-app-mining-timeline).
