### ISSUE TITLE
Reference Principles of Blockstack apps

### ISSUE THREAD

**Issue by friedger** [blockstack/app-mining#38]
Does an app in the app mining program need to follow the principles of Blockstack apps as described in https://docs.blockstack.org/develop/dapp_principles.html#blockstack-dapp-principles ?

**Comment by jeffdomke** [comment]
In short yes, or at least our goal is to do so, that is why we have this epic: Proposal: Blockstack "Good Citizen" reviewer: #8 

I'm suggesting this is a duplicate of that issue and will close.
