### ISSUE TITLE
Should app miners be allowed to submit more than one app for mining?

### ISSUE THREAD

**Issue by thedavidlewis** [blockstack/app-mining#39]
Graphite has two apps ranking in the top 10 in February:
- #1 Graphite https://www.graphitedocs.com/
- #6 Graphite Publishing https://publishing.graphitedocs.com/

If it permissible for an app miner to mine multiple apps, there needs to be rules around what is allowed and what is not or miners will be encouraged to split their apps.

If it is not permissible, there is an incentive for miners to hide the identities of their apps that they split. This would be a community guideline and would have to come with a penalty for breaking it.

**Comment by friedger** [comment]
I think splitting apps is a thing that goes well with "Increasing the quantity .. of apps" from the long term goals. The quality would not suffer as the apps are competing in the same way. It makes it easier for the user to get the idea of the app and to build trust because it is simpler, more focused.

**Comment by jeffdomke** [comment]
I believe this briefly came up in the initial design of the program. I'm not sure there is anything inherently wrong with this? Is there? 

Also, even if we agree to limit an App Miner to one app, how would we police this? Entities, not individuals, can also create apps. And an entity could be made up of other app miners, or combos of them, etc. And people can conceal their identity as well. 

Not sure how this wold work? Open to considering, just need a practical way to deal with complexity above. 👆

**Comment by friedger** [comment]
@thedavidlewis Do you see any other draw backs than splitting apps (which I think is not bad)?

As a guideline, apps from the same publisher should be recognized (e.g. by naming the same producer on the app site).

As discovering apps from the same app publisher is difficult, I suggest to close this issue with reference to the overall goals of the app mining program.

**Comment by jeffdomke** [comment]
OK, per your suggestion I'm closing. Thx @friedger
