### ISSUE TITLE
App Mining Algo: Ping PH to ensure no apps can purchase featured position 

### ISSUE THREAD

**Issue by GinaAbrams** [blockstack/app-mining#4]

**Comment by jeffdomke** [comment]
Next steps: 

- Publish that PH has agreed to this. 
- Update the FAQ.

**Comment by moxiegirl** [comment]
Issue moved to [blockstack/docs.blockstack #119](https://github.com/blockstack/docs.blockstack/issues/119) via [**ZenHub**](https://www.zenhub.com/)
