### ISSUE TITLE
App owner

### ISSUE THREAD

**Issue by MedBTG** [blockstack/app-mining#42]
In my opinion, if the code is not open source it should not be in the app.co/producthunt list at all.  How do you know your data is not being funneled to multiple places.  The code is the only way to tell that.  I am using mywhereabouts on ios.  How do I know my locations are in my bucket only?  I love the app but I posted to producthunt (the only site where I could locate the author) Peter Chmiel, the developer and I have not heard anything.  By no means am I saying Peter's app is siphoning data but I just dont know.  Thats some precious data to be exposed though.  I inquire because, I evaluate every new Blockstack app, for review by my business team.   How do I know I'm not exposing my data during these apps mvp stage?  Thanks for time

**Comment by pstan26** [comment]
Yep! Guessing you mean "app.co/blockstack". This request for Open Source is encompassed in @larrysalibra initial thoughts in https://github.com/blockstack/app-mining/issues/8 and is a perfect job for a "Good Citizen" app reviewer. Excellent idea.

**Comment by larrysalibra** [comment]
Great feedback @MedBTG - open source is very important to the ecosystem, but it's only part of the equation.

The second part is having some software that defends your rights on your behalf and makes sure you're not sharing data without explicitly agreeing to!

**Comment by MedBTG** [comment]
@pstan26.   When I reference app.co/producthunt.  I meant both sites app.co and producthunt should not accept apps with it being open source.  Can you denote on the sites if there is a git repo?.?  That way you can decide whether to run it or not.

@larrysalibra,  As for your second part, I thought that is what BS was doing.  If my team vets all code, there is a good chance no siphoning is happening.  Open Source is great but you have to have trust in the code(r) or dApps act just like siren servers.  You are brilliant Larry keep up the great work

**Comment by jeffdomke** [comment]
@larrysalibra sounds like this might be a good input into your reviewer, assigning to you.

**Comment by jeffdomke** [comment]
@larrysalibra sounds like open source will be included in your reviewer roadmap. Looking forward to that happening soon.

**Comment by jeffdomke** [comment]
Sounds like @larrysalibra might do this in the future which would be great. Closing.
