### ISSUE TITLE
Add links to scoring criteria of app reviewer

### ISSUE THREAD

**Issue by friedger** [blockstack/app-mining#46]
Currently, the site only lists the current app reviewers.

It should have at least a link to a page where the scores and how they are calculated are described.

**Comment by jeffdomke** [comment]
@friedger can you please expand a bit more on this? We already have the criteria in our docs and would only want to reference it in one place. Thx.

**Comment by friedger** [comment]
Yes, I would just like to have a link from this site to the docs to make it easier to discover.

**Comment by jeffdomke** [comment]
@friedger here is a link from the repo to the docs. I assume this is not what you mean, which site exactly and what docs? 

![Screen Shot 2019-03-08 at 10.59.55 AM.png](https://images.zenhubusercontent.com/5c01542d2c4f4d3a813340fc/3eb08cc9-2008-4fff-b343-e737dc23492c)

**Comment by friedger** [comment]
Something like the page for trymui https://github.com/blockstack/app-mining/blob/master/app-reviewers/tmui.md
for all reviewers. These pages could document when, why the reviewer was chosen or removed. All other information relevant for developers should be in the docs

**Comment by jeffdomke** [comment]
@friedger if you want to make an update to the docs please go ahead and open a PR. Thx!
