### ISSUE TITLE
Proposal: Community Audit of App Mining Rankings 

### ISSUE THREAD

**Issue by GinaAbrams** [blockstack/app-mining#49]
In its current state, there is some opacity around the app mining rankings and the payouts until after the payouts are complete. Would like to add a community QA element before the payouts are done. 

Open question is methodology: 
- should we include the whole community, or rotate individuals? 
- Should there be a reviewer who specifically works on this every month? 
- What are the necessary criteria to result in changing the draft of rankings? 

cc @hstove @cuevasm

**Comment by friedger** [comment]
Duplicate of https://github.com/blockstack/app-mining/issues/50
