### ISSUE TITLE
Proposal: Create standard methodology in the event that an app cannot be reviewed by a reviewer

### ISSUE THREAD

**Issue by GinaAbrams** [blockstack/app-mining#51]
Currently, there are some apps that do not qualify to be tested in certain circumstances. E.g. they may need to use another app to be useful, or they may require a certain hardware that is not accessible to everyone. As time goes on and reviewers are added, this will become more and more of an issue. 

Open question: 
- How can we create a method that is fair to the community, while not punishing the app founders when this happens?  

Next steps: 
- Determine said process, add to FAQ.

**Comment by friedger** [comment]
The current method is that it gets a theta score of -1 (with the idea that -1 is not the worst).

**Comment by jeffdomke** [comment]
Sounds like this is related to https://github.com/blockstack/app-mining/issues/35 and is already resolved, closing.

**Comment by friedger** [comment]
I would like to re-open this issue because with the dry run in April shows that it is possible that a half reviewed app can become first place.

**Comment by friedger** [comment]
I see that there is a discussion about this on #91
