### ISSUE TITLE
Proposal: Define criteria for eligible apps

### ISSUE THREAD

**Issue by friedger** [blockstack/app-mining#53]
**What is the problem you are seeing? Please describe.**
The system does not describe objective rules or a method that determines whether a submission is eligible or not.

**How is this problem misaligned with goals of app mining?**
The missing rules 
* can reduce the quality of apps on app.co 
* increases the operational work for Blockstack PBC

**What is the explicit recommendation you’re looking to propose?**
State/document prominently the following rules:

* An app is a web site that is identified by a url or blockstack id (if possible)
* An eligible app is an app that
  * offers the user of the app the possibility to authenticate with the Blockstack auth protocol. The app can offer alternative authentication methods.
  * is not a "hello-world" app
  * was not created as part of a tutorial like "Animal Kingdom" apps
  * is published by an entity that owns an email address, a bitcoin address, that declares what its tax status is in the US.

The final decision of eligibility is determined by the "App Mining Committee". The "App Mining Committee" currently consists of employees of Blockstack PBC. The decision of the committee is final. Apps that are not eligible can be re-submitted for the next round. The eligibility of an app can change from one round to the next.

Apps that provide their main functionality via a mobile app or other hardware should submit an eligible app that users can use in a web browser (maybe with limited functionality).

** Long term considerations
The above mentioned rules favor web applications over mobile native application because there are indications that mobile web browsers are powerful enough to run the same applications as a desktop web browser, because distribution of mobile native applications are strongly centralized

The App Mining Committee could consist of community members that are nominated by the community, maybe on a rotating basis. The committee could consult the community.

**Additional context**

https://html5.rocks

Paper/talk submissions to conferences are following a similar procedure via program committees.

**Comment by friedger** [comment]
Current documentation is in the [App mining FAQ](https://docs.blockstack.org/develop/appminingfaq).

This is partly improved in https://github.com/blockstack/docs.blockstack/pull/158/files
It should be part of the app mining documentation

**Comment by AC-FTW** [comment]
@friedger interesting proposal. Here are some thoughts that pertain to the discussion:

- I find web apps on a phone are often unsatisfying and slow, lacking in first class integration (i.e. notifications), and would have to be miraculous to attain any level of "stickiness"
- I think most of the world's users for most applications are on phones--many people don't own laptops or computers.

Your proposal makes sense for the current state of Blockstack, but to me it doesn't make sense for the direction that I think Blockstack may want to go (maximizing users and the experience). You're certainly right about the centralized nature of App Distribution (and we can extend that to push notifications etc.), but then again there's a lot of centralization in Blockstack Web Apps too (i.e. DNS, number of current GAIA nodes, etc.)

**Comment by friedger** [comment]
@AC-FTW There are efforts on all browser platforms to improve the use of web apps on mobile devices. Recently, the Google Play store opened for (good) web apps, Microsoft Store is already for a long time. This all indicates that web apps will come to mobile devices in the long run.

The proposal is meant for the current state of Blockstack, now. And should be adjusted as we move on. @AC-FTW How would you define eligible apps?

* App Distribution can't be fixed by us.
* Web Push API is coming (https://www.w3.org/TR/push-api)
* Decentralized blockstack app distribution is coming
* More gaia nodes are coming (hopefully), like S4 or Microsoft User storage

**Comment by jeffdomke** [comment]
@friedger We're updating the FAQ with a couple of these. Others are already in the documentation. Guess I'm a bit confused on the intention here? Changing the rules or improving communication of existing rules?

**Comment by AC-FTW** [comment]
@friedger I think you know more than I do about the state of web apps on mobile, but I'd still bet their popularity and wide spread adoption is a long way off if ever in the NA market. In markets where censorship resistance is a priority, I think that the information you mentioned is excellent news.

As for your question:

> How would you define eligible apps?

I agree with everything you said up until you made the Web platform a requirement, for the reasons I mentioned earlier. I also think that there may need to be some additional rules around:

- derivative / duplicate apps from the same author
- expired / non-used / abandoned apps

However, that's not too much of an issue yet.

**Comment by GinaAbrams** [comment]
We've updated the FAQ to reflect the app mining [eligibility](https://app.co/mining#what-qualifies-my-app-to-compete-in-app-mining). We also performed an audit and removed several apps from the running for this month that were lacking a functionality. Think this should help, so I will close this issue in about 5 days or so unless there are other large objections.
