### ISSUE TITLE
Digital Rights reviewer: docking points for indexers

### ISSUE THREAD

**Issue by hstove** [blockstack/app-mining#58]
### I'm opening this to start a discussion, and I'm not personally announcing any hard decisions in this ticket.

**What is the problem you are seeing? Please describe.**
The new digital rights reviewer gives you a 2 for 'usage of Gaia' if you use an indexer. This is in comparison to a 4 if you only use Gaia and no indexer.

**How is this problem misaligned with goals of app mining?**
We want to support apps that aggregate data across many users. Apps like Debut and Travelstack do this, and it's a good feature. Social networks and many other apps require this. I don't think we want to dock points for them.

On the other hand, it is true that these apps don't have good options for users wanting to host their own indexer. However, our current tooling doesn't really make that possible. With collections, there will be much better support for running a local/self-hosted Blockstack app, with collections or not. Until then, it's just not very feasible.

**What is the explicit recommendation you’re looking to propose?**
I personally feel that indexers should not be docked points until collections are implemented. When they are, I'll build in support for p2p syncing between Radiks servers, so you can easily run your own. After that, we can dock points for apps that don't support self-hosting.

** Describe your long term considerations in proposing this change. Please include the ways you can predict this recommendation could go wrong and possible ways mitigate.**
I think we want to support social/aggregation apps. We've put out a call for social apps in the past. Penalizing them only discourages their creation.

**Comment by ntheile** [comment]
100% agree with Hanks statement:

> I personally feel that indexers should not be punished until collections are implemented.

**Comment by kkomaz** [comment]
Another 100% agree with this.

If using an indexer like Radiks gives you lower score why is the Blockstack team advertising usage via email, twitter, newsletter, and virtual webinars?  Good catch on this one @hstove , it seems like I might have missed in the criteria 👍

**Comment by jcnelson** [comment]
If users are able to choose which Radiks server they use for an app (or equivalent for custom indexers), would this address any "centralization" concerns?  I wouldn't need to use the developer's chosen indexer; in the limit, I could spin up my own and use that instead.

**Comment by jeffdomke** [comment]
Seems like the actual desired result is: 

1. Larry defines some desired criteria
2. Team/community refines Radiks to meet criteria / get as close as possible. 
3. Our new and improved Radiks become gold standard and we rank off of that as best-possible-solution for indexers.

**Comment by jcnelson** [comment]
Especially considering that the roadmap for Radiks is to make the server decentralized -- each server for a particular app would maintain and replicate a full index in a p2p fashion, thereby separating the act of maintaining an index from the act of developing and maintaining an app.

**Comment by kkomaz** [comment]
Is it possible not to dock for indexers until a better solution exists like collections?  After collections is implemented in the Blockstack system, developers can receive a grace period to transition from indexers to collections.  

Right now as it stands, without an indexer, it discourages building somewhat complex applications that rely on relationships amongst users.  This point "dock" would further hurt apps like debut who already on the bottom of the app mining criteria and further push apps that are notes/blog based to the top.

**Comment by dantrevino** [comment]
As someone who does not use an indexer, I believe current Radiks users should not be docked, since this is a tool that Blockstack was touting.  When the fully decentralized Radiks is available existing apps should be given a reasonable time to upgrade/convert, then be penalized.

**Comment by GinaAbrams** [comment]
Tagging @larrysalibra to please update ASAP. 🙏

**Comment by larrysalibra** [comment]
> As someone who does not use an indexer, I believe current Radiks users should not be docked, since this is a tool that Blockstack was touting. When the fully decentralized Radiks is available existing apps should be given a reasonable time to upgrade/convert, then be penalized.

Totally agree with @dantrevino @kkomaz @hstove and others.

We won't be giving different scores for using gaia by itself and using gaia with an indexer going forward.

Thanks for the feedback everyone!

**Comment by DILIPSKUMAR1410** [comment]
@larrysalibra Can you explain how you are testing whether an app is using gaia and auth ?

**Comment by GinaAbrams** [comment]
Thanks @larrysalibra! 

@DILIPSKUMAR1410 I believe issue #79 and #59 address your question, and if not please create a new issue. 🙏 

I am going to close this as the original issue has been resolved.
