### ISSUE TITLE
Digital Rights reviewer: Mobile apps get punished in their 'gaia' score

### ISSUE THREAD

**Issue by hstove** [blockstack/app-mining#59]
### I'm opening this to start a discussion, and I'm not personally announcing any hard decisions in this ticket.

**What is the problem you are seeing? Please describe.**
The new digital rights reviewer gives you a 0 for 'usage of Gaia' if you have a mobile app. This is in comparison to a 4 if you have a desktop app. The reasoning is because it's hard to verify if Gaia is used in a mobile app - it's more of a closed ecosystem.

**How is this problem misaligned with goals of app mining?**
I think we want to support mobile apps - hence why we build SDKs for them.

On the other hand, it is true that mobile apps are more of a closed ecosystem, and are harder to audit.

**What is the explicit recommendation you’re looking to propose?**
I think there is more you can do to verify that a mobile app uses Gaia. You can run your own Gaia hub, and verify that data is stored in it when you use the app. You can also run a proxy to inspect network requests from the app. This is better than giving them all a zero.

**Comment by andresousa** [comment]
This shouldn't happen.
If the code is open-source, it's easy to verify if Gaia is used.
I have just submitted an iOS app on the App Store for review which only uses Gaia for storage (https://github.com/andresousa/scannie).

**Comment by GinaAbrams** [comment]
@larrysalibra is there an update on this question? Also referenced in #60

**Comment by larrysalibra** [comment]
In the near term, our plan is to set up a custom gaia hub and exam the app's use of the gaia hub so that mobile apps are treated fairly. As an added benefit, we'll be able to verify that apps work properly with user specified gaia hubs and not only just with the default gaia hub provided by Blockstack PBC.

**Comment by jeffdomke** [comment]
Sounds like @larrysalibra's solution works, marking done.
