### ISSUE TITLE
Proposal: Reviewer based on storage

### ISSUE THREAD

**Issue by jeffdomke** [blockstack/app-mining#6]
Assume we would primarily encourage use of decentralized storage vs. centralized. However there might be specific parameters for Gaia vs. other solutions. Also, might include user onboarding and how easy/fast/simple the app makes storage.

**Comment by xanbots** [comment]
Jude and I sat down to brainstorm some thoughts on this. Think ultimately this reviewer could and maybe should also cover the needs for a reviewer that looks at open source and onboarding.

This reviewer should accomplish the job of rewarding apps that are using Gaia over apps that are not, and additionally reward apps that are encrypting that data over those that are not.

Jude and I came up with a potential near term solution, and two options for a more permanent, programmatic solution we can start to move towards. 

**Near Term Solution**
Require all apps participating in App Mining to record and submit a new youtube video each month that includes the following:

- Using a throwaway ID, auth into the app
- Show app data being dumped into a Gaia hub
- Using the Blockstack CLI pull that data out and deencrypt it

The above solves a few problems. (1) proves whether an app is using Gaia and encrypting data, (2) provides nice visuals to show a user their data is secure/not copied, and (3) demonstrates to users they can get their data out of the app.

These videos should be short (no more than a few minutes), and Jude would create a sample that could be followed/copied. 

Please comment thoughts/feedback. Will post the longer term solutions in a subsequent comment.

**Comment by jeffdomke** [comment]
Covered by New Internet Labs reviewer. Closing.
