### ISSUE TITLE
Proposal: Peer reviewer

### ISSUE THREAD

**Issue by friedger** [blockstack/app-mining#63]
As mentioned in the forum [here](https://forum.blockstack.org/t/march-2019-app-mining-results/7685/8) app publishers should be able to rate apps with regards to
* ~~engagement in the developer community and~~
* progress in the development of the application

**Comment by friedger** [comment]
Comment: "it’s susceptible to collusion very very easily"

**Comment by jackveiga** [comment]
- voting cast process transparent (using something like Google Sheet to see who voted in who)
- disallow votes to go all to one app
- disallow voters to vote consecutive months in the same app

**Comment by friedger** [comment]
@paulamdb @hstove Could you setup a clone of vote.blockstack.org that would allow app publishers to vote and comment on apps? It could be just an experiment that does not impact the ranking, but it could indicate if app mining program and expectations of the app miners differs too much.

**Comment by thedavidlewis** [comment]
@friedger Funny thing... I mentioned the same to @pstan26 yesterday. I think it would be great for DE to run it as it would provide great insights on voting ecosystems. It would require game theorists to devise an algorithm that properly rewards and penalizes votes based on their voting behavior. Basically, they would need to create a variation of the Prisoner's Dilemma to stop self-voting and vote trading.

It would be interesting for all involved to see if this surfaced better results of the apps that are most deserving of app mining rewards. (I think OI Calendar deserves far more than 5 votes but I have zero votes to give.)

**Comment by avthars** [comment]
How do we protect against collusion? That's the big question. Is collusion something we're concerned about?

**Comment by avthars** [comment]
> @paulamlb @hstove Could you setup a clone of vote.blockstack.org that would allow app publishers to vote and comment on apps? It could be just an experiment that does not impact the ranking, but it could indicate if app mining program and expectations of the app miners differs too much.

I'd be interested to see this result btw

**Comment by dantrevino** [comment]
Could maybe use @cryptocracy for peer voting.

**Comment by cryptocracy** [comment]
> Could maybe use @cryptocracy for peer voting.

Thanks for the mention @dantrevino ... 

However I think this would be premature at this time given the state of Cryptocracy is still pre-MVP
Furthermore this probably need significant discussions about the exact logistics and the UX to ensure the expectations are met.

Also this would be probably considered a conflict of interest for Cryptocracy, if it were to actually participate in the app mining as a reviewer and a app developer. (even tho votes are capable of being audited by any 3rd party, since the user votes live in their gaia storage.)

**Comment by Pierre-Gilles** [comment]
I'm really worried this will lead to people playing politics inside the developer community, and it'll not really improve the quality of apps, just everyone trying to show to everyone that they are nice developer.

The goal of the app mining challenge is to make developer build great app, not to be the good student in front of other peers.

I think if there are issues with specific apps which seems not to follow the rules, there should just be a discussion with Blockstack/the community to work on this particular case and fix that.

Right now there are just 55 apps on the app mining challenge, I don't think we are at the scale where it's hard to handle specific cases :)

**Comment by friedger** [comment]
I agree that "engagement in the developer community" should not be part of the app mining algorithms as it does not align with the criteria of the program.

**Comment by hstove** [comment]
I think we (and myself personally) are interested in letting app miners vote on different apps, maybe on a Democracy Earth platform. I don't think it would be good to force voters to vote on some criteria like 'active development', they should be able to vote on whatever criteria they want (similar to how DE currently works). This is something we'll continue talking about with DE and potentially make progress, but right now still just an idea.

I also am concerned about internal collusion. It seems likely that app developers would vote on app devs they are friendly with, for example.

**Comment by friedger** [comment]
With OI App Center (https://app-center.openintents.org), everybody (including peers, users, investors) has now the possibility to rate all apps.

As this is too easy to game especially with a low number of users, it should not be part of the app reviewers but can give an indication of which apps are liked or not.

**Comment by friedger** [comment]
Peers should flag apps that break the rules, not give scores.
