### ISSUE TITLE
Blockstack PBC should be allowed to use apps of the app mining program

### ISSUE THREAD

**Issue by friedger** [blockstack/app-mining#65]
There are document, blog post, calendar, chat apps that take part in the app mining program that could be useful to Blockstack PBC. 

This is to discuss whether "used by Blockstack PBC" would be an unfair advantage in the app mining program.

**Comment by jackveiga** [comment]
Maybe open-source could be part of the answer for this? If an app is open-source PBC mitigates the risk if the creator(s) decide to abandon or stop development. It should be important for PBC to know that its investment in the app mining program is safeguarded by having the app code openly avaiable online.

It also allows for reviewers to evaluate the repo as discussed on #11 which would benefit the program review as it allows all the stakeholders involved to see what is actually being done during the month when it comes to development by looking at issues, engagement, prs and commits.

**Comment by thedavidlewis** [comment]
@friedger That's a great question. I agree that Blockstack PBC should drink its own Kool-Aid and use App Miners. OI Calendar should be used over Google Calendar. Graphite over Google Docs or Office 365. There are 2 issues with:

1) If there are multiple App Miners for a single function (e.g. calendar), is it fair for Blockstack to pick? And if Blockstack does pick one, what if a better dapp is launched or a dapp not chosen gets a massive improvement? Should Blockstack PBC change each time?

2) Many dapps aren't B2B so there isn't a reason for Blockstack PBC to state it uses them. Would this place them at a disadvantage for voting to dapps that are used by Blockstack PBC?

**Comment by friedger** [comment]
The rating algorithms should not take into account that Blockstack PBC is using an app or not, so ideally there is no advantage or disadvantage if Blockstack PBC.

@thedavidlewis 
Re 1, it is up to Blockstack PBC (and any other user) to use an app or not or replace it with some other apps at any time. It is mainly a operational question.
Re 2. ideally it does not matter.

I think that "used by Blockstack PBC" is 
* a marketing advantage for the app. 
* good for the ecosystem
* not hurting the app mining algorithms.

**Comment by dantrevino** [comment]
IMHO, that kind of endorsement would likely impact new apps getting started in the same niche.  I.e. would likely hurt competition.  I would like to see Blockstack PBC actually using Blockstack Dapps though. Tough one.

**Comment by friedger** [comment]
Competition with regard to what? Awareness probably. Too bad we want such a
reviewer.

Closing this one.
