### ISSUE TITLE
Democracy Earth: Ask investors for feedback on apps

### ISSUE THREAD

**Issue by friedger** [blockstack/app-mining#66]
**What is the problem you are seeing? Please describe.**
App publishers do not get any feedback why the received up or down votes

**How is this problem misaligned with goals of app mining?**
App publishers can't improve their product because the rating of DE is not backed by information

**What is the explicit recommendation you’re looking to propose?**
* Require voters to post at least a one liner
* Create a communication channel between app publishers and DE voters.

**Additional context**
Mentioned in https://forum.blockstack.org/t/march-2019-app-mining-results/7685/4 and https://github.com/blockstack/app-mining/issues/61

**Comment by blockcred** [comment]
Totally agree 
In addition ... DE has no tools for filtering or ranking to help App miners to get better insights on the spot, everyone should go manually and calculate his position according to others.
No notification received for any action (upvote, downvote, debates opened ... etc )

**Comment by jyudkin1** [comment]
I think the real issue here above all is retention on Dem.Earth voters .... there is a memory function problem. Someone scores something 2 months ago, allocates all of their votes, and does not come back. Huge advantage for early miners - huge disadvantage for new apps. 

I think that engagement would solve these issues of transparency. Miners are operating under an assumption of active participation, when in reality it is not that active (from what we can tell). This is a simple fix.

**Comment by cryptocracy** [comment]
> Require voters to post at least a one liner.

YES PLZ! ... With indications that goes over why, or why they didn't vote on the app:
This A gives us feedback to work with, as well as B gives confidence we are actually being reviewed. (as someone who experience multiple months straight with a deafening silence on DE, i can tell you its frustrating, especially when Cryptocracy is actually some what similar to DE itself)

**Comment by GinaAbrams** [comment]
This is an interesting idea for the future. The team has been heads down working on a test of quadratic voting so this will not be implemented for this round (full transparency, nor will quadratic voting, but it is in progress). Think a good next step would be to stack rank this potential feature with other requests of the platform and have a list to proceed for the coming months.

**Comment by GinaAbrams** [comment]
Closing this given the decision on #92.
