### ISSUE TITLE
Digital Rights reviewer: insecure apps get full score (lioapp)

### ISSUE THREAD

**Issue by friedger** [blockstack/app-mining#68]
The lioapp get score 4,4 but is hosted on http domain, not https

**Comment by jeffdomke** [comment]
hey @larrysalibra can you please address this.

**Comment by larrysalibra** [comment]
Using https seems like it should be a basic criteria for app mining eligibility.  We can create a policy to catch these and flag these during our review, but it seems like something that can be caught before app mining reviews even starts either by looking at the list or making the application form not accept URLs that don't start with https://. Thoughts @hstove @GinaAbrams @pstan26 ?

**Comment by jeffdomke** [comment]
Sounds like the next step is to update our docs with an `https` requirement.

**Comment by GinaAbrams** [comment]
Asked about this in [#201](https://github.com/blockstack/docs.blockstack/issues/201).
