### ISSUE TITLE
Base product rated/promoted instead of Blockstack product (Gladys)

### ISSUE THREAD

**Issue by friedger** [blockstack/app-mining#70]
The product listed as "Gladys" on https://app.co/app/gladys directs the user 
* to the base product page (https://gladysproject.com/ claiming to have 35k users) that is needed to make use of the blockstack related product, instead of directing the user the blockstack related product (https://developer.gladysassistant.com/en/modules/blockstack)
* to the github page of the base product (https://github.com/gladysassistant/gladys-blockstack) instead of the blockstack related product (https://github.com/GladysAssistant/gladys-blockstack)
* to the product hunt page of the base product instead the blockstack related product (https://www.producthunt.com/posts/gladys)

For the twitter account, it shouldn't be a problem if the base product and blockstack related product is develop by the same publisher even though it will affect the popularity on app.co sorting.

**Expected action**
* Install a "whistle blowing system" that allows community members to flag incorrect information.
* Correct information on app.co
* require a different page on PH
* create a new entry on DE

**Additional context**
OI ConvertCSV provides comparable features and setup:
* uses a base product (OI Shopping List or OI Notepad vs Gladys Assistant)
* allows users to backup and restore a single file
* does not work on the web (Android only vs Gladys Assistant on Raspberry PI)

OI ConvertCSV is ranked 51 (I am fine with that)
Gladys is ranked 4 (why?)

I could have linked to [OI Shopping List](https://play.google.com/store/apps/details?id=org.openintents.shopping) with more than 1M+ users, 4.3/5 ranking, translations into 40 languages etc. but that wouldn't reflect the part that is related to blockstack.

**Comment by Pierre-Gilles** [comment]
Hey! Founder of Gladys here.

On current Gladys version (3.12), Gladys is coded as a modular system, which means that Gladys code is splitted across many different repositories, but at the end when you install it, it's a **single product**.

Why do you want to blame repositories architecture choices?

By the way, next major version of Gladys (Gladys 4) will be a mono-repo, with Blockstack code in the main gladysassistant/gladys repository, so no more confusion :)

I understand it can be misleading, but understand it's just an repo-architecture choice. (Like Blockstack as different repo for all its components).

**Comment by friedger** [comment]
@Pierre-Gilles I understood that the module is optional.

Still, you receive high score e.g. on Product Hunt because the audience rate the digital assistant (which is a great product). However, the app mining algorithms should take into account that the part which involves blockstack is only related to backup and restore of preferences.

**Comment by Pierre-Gilles** [comment]
I commented here with a more global view of Gladys-Blockstack integration => https://github.com/blockstack/app-mining/issues/64#issuecomment-475179600

Gladys is a physical product, which by default is not sending data to the internet. As discussed with Blockstack team during the development, we thought it was a good idea to allow users to store their home automation setup in Gaia.

But I don't see how it is a difference from any other Blockstack app?

Any blockstack app is a client-side application which backup the data in the cloud when the user is not using the app, and restore the content when the user is back. Same with Gladys.

**Comment by friedger** [comment]
@Pierre-Gilles My question here is whether Gladys as physical product should be rated by the algorithms or the optional module, whether OI Shopping List or OI ConvertCSV should be rated and finally, whether an app (like OI Timesheet or Graphite) that works without blockstack should be rated differently.

**Comment by Pierre-Gilles** [comment]
I see your point, but here the code is (currently) separated in a different repo just by architecture choice, at the end you sync your Gladys data with Blockstack inside Gladys. It's the same app.

It's exactly like any other Blockstack app... (which can have different way of logging in)

And as I said, in the next release all the code will be under the same repo, this will not be anymore a separate thing :) (but it won't change anything for the end-user)

I think we need to see all that through Blockstack point of view and with their interest in mind.

They are definitely happy to communicate on the fact that a big & already established open-source projects integrated Blockstack. It's in their interest to have nice brands like Gladys in their portfolio of app, no?

I don't know exactly how OI Shopping List/OI ConvertCSV works, but if you integrated Blockstack into OI Shopping List, just publish it on the App Mining challenge :) 

By the way, the title of this issue is (ironically) now a little misleading regarding Gladys, could you close this issue? :) 

Thanks.

**Comment by friedger** [comment]
I don't know how the modules will look like in version 4, until then I still think that the algorithms should rate the blockstack module (compares to OI ConvertCSV) and not Gladys as a whole (compares to OI Shopping List) 

The algorithms should not be by influenced by marketing efforts of Blockstack PBC. 

How the OI apps work: By installing OI ConvertCSV, a menu entry is added to OI Shopping List that allows you to backup and restore data.

I have rephrased the subject of this issue. I still don't have a conclusive answer how the algorithms should deal with such cases and there might be more coming up. Taking it to an extreme, what if I submit an app platform (like lineageos or brave) that allows you to install an app that uses Blockstack. Should the phone/browser be rated or the app? 

Or more openly, how should features that work without Blockstack be taken into account?

**Comment by friedger** [comment]
I still think that a visitor of gladysassistant.com is not well informed about how Blockstack is integrated in the assistant.
1. A user of Gladys have to create an account on Gladys using email and personal data. This account is not related to the Blockstack ID
1. For me, I had to run an extra script to enable SSL on Raspberry PI such that the hosted Blockstack Browser would log me in.
1. In order to make use of any features related to Blockstack, a separate module needs to be installed (as described in the news headline). It says "You can now easily sync your Gladys Home preferences in the BlockStack network. " However, it is only possible to manual upload and download preferences that are set in a sub menu of the parameter menu. All the other preferences, like definition of house, rooms, devices, even the user specific parameters in the above mentioned submenu are not touched by Blockstack upload-download feature.

@larrysalibra For the Gladys application this should result in 0 points in the NIL review for not using Blockstack auth. Maybe 1 point could be given because it is used secondarily if the user installed the module and uses the upload-download feature.

**Comment by larrysalibra** [comment]
@friedger I didn't review Gladys as it requires hardware we don't have. My understanding is that it was marked ineligible for New Internet Labs review by the PBC app mining team.

**Comment by friedger** [comment]
I am concerned that an app gets top ranked that is not a top blockstack app
IMHO applying as much objective data as possible.

**Comment by larrysalibra** [comment]
I was looking more deeply into this today. 

> On current Gladys version (3.12), Gladys is coded as a modular system, which means that Gladys code is splitted across many different repositories, but at the end when you install it, it's a single product.

> Why do you want to blame repositories architecture choices?

@Pierre-Gilles I don't think there's any problem with developing an app in separate repos. The concern comes with how they are shipped to the user. If users can't use Blockstack with the default installation of the app, it seems to me that it isn't a Blockstack app.

For example, there's a Blockstack plugin for discourse. The mere existence of this plugin doesn't make discourse a Blockstack app. If discourse started shipping the Blockstack plugin configured and activated with their default installation, then one could argue that discourse is a Blockstack app.

In my view, apps that are modular should include the Blockstack functionality installed and activated by default to be eligible for app mining.

**Comment by Pierre-Gilles** [comment]
@larrysalibra Thanks for your feedback 🙏

We discussed with @GinaAbrams on the phone at the end of last year before implementing this, and at the time we agreed that doing the integration this way as a first step was enough.

I completely agree that it's not optimal and since December 2018, I've been working full-time on the next major version of Gladys, Gladys 4, with the goal of merging all plugins into the main repo, so it'll more looks like what you are expecting.

Here is how the signup looks like in Gladys 4 ⬇️

<img width="1440" alt="Screenshot 2019-04-29 at 13 18 02" src="https://user-images.githubusercontent.com/7365207/56951723-30b46900-6b56-11e9-899b-e2846bb30158.png">

**Comment by Pierre-Gilles** [comment]
And just a little addition, as Gladys is fully self-hosted (on a hardware you have at home), if you provide sensitive informations to Gladys, you just save them locally on the local database of your Raspberry Pi. So it's fully "local", nothing leaves your house 🙂

It's not fair to compare Gladys to a traditional server application, your local installation of Gladys is not a third-party, it should be considered as a client, it's like saving informations in the LocalStorage of the browser.

(Exactly as Blockstack browser is a server installed on the client-side)

**Comment by friedger** [comment]
The app mining process has evolved and I hope that decisions are not made by a single person on the phone anymore.

@Pierre-Gilles This issue is not about the architecture of your code.

I think Gladys 3 should be rated as not using auth (as it requires extra configuration that are not obvious and be excluded from app mining) or at least broken auth (as it requires extra fixing to make it work with the browser and https).

Just to be clear, I also think that Gladys is good in protecting digital rights, but not (yet) so good in using Blockstack.

**Comment by Pierre-Gilles** [comment]
@friedger I think there is a little conflict of interest in this discussion, and I'm wondering if it's good to discuss that between app miners. It seems you mainly want to remove other apps from the challenge rather than trying to find ways to improve those integrations.

I explained why the integration is like that and I'm open since the beginning to make improvements to this integration (see my recent work above).

**Comment by friedger** [comment]
@Pierre-Gilles I am happy to stop giving my input here if there are more contributions by others. I try to be open about my interests and also point out where my apps fail to excel. Here, I try to speak as a user:

When I looked at the source code and when tried Gladys (v3) I was disappointed about the way Blockstack was used. Hence, I opened this issue.

**Comment by kkomaz** [comment]
I don't have a strong opinion about gladys specifically.  I think it's more of issues like this

> We discussed with @GinaAbrams on the phone at the end of last year before implementing this, and at the time we agreed that doing the integration this way as a first step was enough.

The lack of clarity behind what is the exact rules and what determines an app being eligible is the biggest flaw in the system.  An action like above allows apps to bypass certain criteria by no fault of the app developer.  I realize we shouldn't discourage apps from participating but better eligibility criteria can avoid conversations like this.

**Comment by GinaAbrams** [comment]
Hey folks, seems like there are several issues here:
1) base product vs. promoted.
2) process for whistleblowing.
3) eligibility requirements.

Can we open new issues for any of the above? 🙏 Also, I was and am a main point of contact but do not act without input from the whole PBC team.

**Comment by Pierre-Gilles** [comment]
@kkomaz 100% agree! I think it's just a lack of clarity that brought this discussion. We all want to implement Blockstack the correct way and are open to changes.

**Comment by friedger** [comment]
Closing this one in favor of #100
