### ISSUE TITLE
TryMyUI: Proposal to focus UX test on using the app, not on onboarding

### ISSUE THREAD

**Issue by friedger** [blockstack/app-mining#71]
**What is the problem you are seeing? Please describe.**
TryMyUI tester sometimes do not get past the blockstack login or rate the blockstack.org page instead of the app.

**How is this problem misaligned with goals of app mining?**
The score does not reflect AFL if the rating is not towards the app.

**What is the explicit recommendation you’re looking to propose?**
Require the tester to perform a simple task like 
`Create a new todo item on https://blockstack-todos.appartisan.com/`
before they view the application.

** Describe your long term considerations in proposing this change. Please include the ways you can predict this recommendation could go wrong and possible ways mitigate.**
While this reduces the review of onboarding we have #5 to solve this.

**Additional context**
#1 about the audience is still open

**Comment by jeffdomke** [comment]
I've heard a few reports of the testers not getting into the app. If my memory is correct, TryMyUI should have instructions that the test must login. Also they have some review procedures in place to retest bad sessions. If that is not happening, we need to identify the problem clearly and ask TryMyUI to fix the issue. @GinaAbrams anything to add here? cc @markmhx

**Comment by cryptocracy** [comment]
I fully agree with the sentiment being expressed here.
Having to educate the users about intricacies of Blockstack while also trying to educate them on the features of a complex app, leaves a lot of the uninitiated simply scratching there heads rather then testing the apps.

**Comment by jeffdomke** [comment]
In the real world, to be successful as an app developer, you will need to educate customers on what Blockstack is and why they should value it. And if you do that well, obviously it is good for your app, but also for the customers. And it is good for everyone in our ecosystem. 

We could create artificially educated users for testing to take the pressure off apps. It will be easier for app devs in the short run, terrible for the ecosystem in the long run. 

In general I would suggest we want to reward apps that do a better job introducing new users to Blockstack. Are there other ideas to address this problem while still maintaining that principle?

**Comment by friedger** [comment]
> terrible for the ecosystem in the long run.
It depends where you see the boundaries of the ecosystem. If it ends where Blockstack is required then yes, but there are more decentralized identity providers and apps should embrace them all (But not teach their users about each of them. In the current world it does not hurt when apps do not explain the difference between github, google, facebook logins)

Furthermore, the goal of the app mining program is to encourage
> Discovery and distribution of apps to users that want them.

TryMyUI is not doing good in choosing "users that want them [the apps]", therefore, doing a dry run would help here.

**Comment by jeffdomke** [comment]
Sorry, I can't agree on the grounds of my earlier argument: 
>I would suggest we want to reward apps that do a better job introducing new users to Blockstack. 

There is a ticket for improving the TryMyUI audiences here: https://github.com/blockstack/app-mining/issues/1

**Comment by friedger** [comment]
@jeffdomke I assume you are referring to
> Expanding consumer awareness of Blockstack ID and decentralized auth/storage.

So, the conclusion is that
* apps should do a good job on onboarding users (Blockstack could develop Animal Kingdom or Banter into an app that demonstrates good onboarding process)
* app publishers should review their TMUI scores and complain to TMUI when the tester didn't test or did not finish testing the app, but gave scores based on impressions outside of the app.
