### ISSUE TITLE
Democracy Earth: Reset votes at some interval

### ISSUE THREAD

**Issue by friedger** [blockstack/app-mining#72]
**What is the problem you are seeing? Please describe.**
Votes on DE do not change even though the application has improved.
Votes on DE do not change even though the application has **not** improved.

**How is this problem misaligned with goals of app mining?**
The Score of DE does not give any indication about the state of the product, whether it is a high quality app or not, because the score does not change if the app changes.

**What is the explicit recommendation you’re looking to propose?**
* Reset the votes three months 
* Reward voters if they come back
* Add valuable members of the blockstack ecosystem to DE as voters ("renewable membership" every three months)
* change the width (?) of the normalization related to the number of votes given. If there are only a few apps that received votes/only a few votes have been given then all apps are close to 0 in the score, if all apps received some votes/all votes have been used then use the current formula.

** Describe your long term considerations in proposing this change. Please include the ways you can predict this recommendation could go wrong and possible ways mitigate.**

**Additional context**
See to #63 for a proposal to clone vote.blockstack.org to be used by app publishers

**Comment by cryptocracy** [comment]
I fully agree!

Cryptocracy opted to be part of the pilot app mining, and we were well away from being to a MVP at that time, but unfortunately DE traction seems non existent for Cryptocracy.

We literally 0 DE votes and 0 comments, until this last March mining period. (which would seem to indicate that once we were closer to MVP we are more appealing?)

I also have concerns that voters are not searching very thoroughly through the list of apps since comments are pretty sparse all the way around. 

Anyways, I'm not trying to sound like I'm complaining, because I'm not, I've still very optimistic about App mining as a whole.

**Comment by jeffdomke** [comment]
Have a specific suggestion for the votes? Should they simply reset/expire each month? I read expire after 3 months? Should they decay at a certain rate?

**Comment by jackveiga** [comment]
If DE voters were more active a 3 months expiration might be good to avoid votes jumping, but since they are not at least at this stage, I think that a simple reset/expire each month would be fairer to everyone involved.

**Comment by muneebm** [comment]
I agree with @jackveiga here. I think a reset before each round would encourage more voters to reallocate their votes based on current status of the apps they previously voted and this also gives new apps a fairer chance to get votes.

**Comment by friedger** [comment]
A monthly reset is good as well. The tools should help voters to easily
review their last months votes.

**Comment by kkomaz** [comment]
@GinaAbrams // @jeffdomke 

Any update on this one?

**Comment by GinaAbrams** [comment]
We're working on this and plan to have an update here next week. Thanks for your patience. 🙏

**Comment by GinaAbrams** [comment]
Closing this as well given the decision on #92.
