### ISSUE TITLE
Proposal: Reward apps with similar code base only once

### ISSUE THREAD

**Issue by friedger** [blockstack/app-mining#75]
**What is the problem you are seeing? Please describe.**
In #11 it is mentioned that open-source apps could be copied and submitted under a different name more easily than close-source apps. 

**How is this problem misaligned with goals of app mining?**
This does not accelerate the adoption of high quality apps that preserve individual’s fundamental digital rights because developers fear that their product will be copied and re-submitted.

**What is the explicit recommendation you’re looking to propose?**
Reject apps that can't prove that they are different to existing apps. A peer reviewer (#63) could help to identify similar code base.

** Describe your long term considerations in proposing this change. Please include the ways you can predict this recommendation could go wrong and possible ways mitigate.**
This requires that all accepted app are open source.

Proof of difference could be for example rejected feature requests or pull requests.

This proposal might discourage new submissions of the same product with massive improvements, however, the innovation can take place in the open source product.

**Additional context**
Product development #64 
gitcoin.co
closed issue about similar apps (different code base) #37

**Comment by GinaAbrams** [comment]
Hey @friedger it seems like this may be trying to solve a problem that doesn't exist yet, at least to my knowledge (feel free to correct me if I'm wrong). PBC is the facilitator now but this will further decentralize in the future, and I'd be hesitant to over-engineer and become an arbitrator in disagreements such as these down the line.

**Comment by friedger** [comment]
It directly effects the opinion about the requirement for apps being open
source

**Comment by friedger** [comment]
Closed by #113
