### ISSUE TITLE
Better manage expectation of developers

### ISSUE THREAD

**Issue by friedger** [blockstack/app-mining#76]
**What is the problem you are seeing? Please describe.**
It is not clear from the publicly available information
* that algorithms will change over time
* that this is an experiment
* 

**How is this problem misaligned with goals of app mining?**
If app publishers gets disappointed they won't create/improve apps, hence less good apps.

**Comment by jeffdomke** [comment]
Can you please add more detail of where this language is incorrect / should be changed?

**Comment by friedger** [comment]
@jeffdomke It was mentioned in the app miner video call that an issue should be opened for that.

The story starting at app.co/mining until the last sentence of the [docs](https://docs.blockstack.org/develop/mining_intro.html) does not really mention 
* that the rules might change every month, (and that app miners can make suggestions to change the rules maybe even into their favor).
* that founders who want to build apps that respect digital rights are more welcome than founders who want to make quick money, and that the algorithm try to detect that.

Some concrete suggestions:
* Start on app.co/mining below "Get started with App Mining." with "Learn" (about digital rights) and then "build"
* Use sometime "product" instead of "app", e.g. "Register your user-ready product at app.co", "Improve your product. Improve your rank..."
* Use "rewarded" instead of "paid" e.g. in ["Founders that build apps using Blockstack developer tools like Blockstack Auth get paid each month .."](https://docs.blockstack.org/develop/mining_intro.html#what-is-app-mining)

**Comment by friedger** [comment]
After discussion on #71 , clarify on app.co that a submission is of two parts
1. product page where users are educated about the product and blockstack id and decentralized auth/storage
1. the product itself

**Comment by jeffdomke** [comment]
@ friedger not sure I agree with these changes, or that they would help in the intended way, but feel free to open PRs on app.co or our docs.
