### ISSUE TITLE
PH: Change ranking input to number of upvotes this month

### ISSUE THREAD

**Issue by jeffdomke** [blockstack/app-mining#78]
@jeffdomke commented on [Fri Mar 22 2019](https://github.com/blockstack/app.co/issues/480)

Idea is to eliminate apps having a long term advantage based on a one time launch. And if apps want to find ways to boost upvotes post-launch that is fine.

**Comment by friedger** [comment]
@jeffdomke Do you have insight about how many upvotes a product gets one, two, three month after hunting?

I see PH as a score how successful the launch was. This encourage app publishers to prepare the launch as good as possible. Is it fair to products that have already launched? My understanding is that you can relaunch as well.

**Comment by jeffdomke** [comment]
> I see PH as a score how successful the launch was

Yes, and with this change, apps would only get a boost for the month they launched. I'm proposing we can fix PH but making the impact on ranking more true to the fact that PH is more of a one time thing vs. a perpetual signal of app quality.

**Comment by friedger** [comment]
I like the idea of "launch boost"! App publishers can get a bit more rewards in the first month and start from there.

@jeffdomke Is this gameable by re-launching every two or three month?

**Comment by jeffdomke** [comment]
We spoke with PH and they will supply this number to us as well, and we'll look at the data and decide if this change makes sense. But closing this for now since the change isn't happening yet.
