### ISSUE TITLE
Digital rights reviewer: understanding the criteria 

### ISSUE THREAD

**Issue by geeogi** [blockstack/app-mining#79]
Hi there,

We at [Zinc](https://zinc.work) are keen to improve our understanding and implementation of Blockstack with respect to the user’s digital rights. I have a few questions regarding the criteria of the digital rights review. Hopefully this is the right place to ask. Many thanks in advance. 

## Blockstack auth
 
- [ ] Does the blockstack auth in our app need to be compatible with all browsers? If not, which ones? 
- [x] When Blockstack auth is offered as one of many options, what exactly differentiates between "secondary", "equal" and "primary" importance? 
> See PDF: [Auth.Scoring.pdf](https://github.com/blockstack/app-mining/files/3017070/Auth.Scoring.pdf) 

## GAIA

- [x] To score 4/4, must GAIA be the sole storage for all users? Or just for those who authenticate with Blockstack? 
- [x] To score 2/4, must GAIA be used for all users? Or just for those who authenticate with Blockstack? 
- [x] To score 2/4, can GAIA be used in a write-only manner on the app? 

> See: https://github.com/blockstack/app-mining/issues/79#issuecomment-477502343

## Feedback

- [x] Is feedback offered on "broken" scores? 

> Feedback was given via comment in this thread: https://github.com/blockstack/app-mining/issues/60

**Comment by friedger** [comment]
referencing also #46

**Comment by xanbots** [comment]
@larrysalibra

**Comment by larrysalibra** [comment]
I've put together a doc with some quick sketches of how I think about authentication scoring:

[Auth Scoring.pdf](https://github.com/blockstack/app-mining/files/3016837/Auth.Scoring.pdf

Apologies for my drawing skills.

Re gaia, as mentioned in #58, going forward, we won't be treating apps that use gaia and in additional to 3rd party storage differently. There will only be 3 scores - uses gaia, doesn't use gaia or broken.

Our goal here is to reward developers that use gaia as a place to securely store the canonical copy of the data they generate using an an app and do it in a way where the developer never has access to encryption keys.

Initially, we're not going to be incredibly strict on this, but your best bet to be well-positioned for the future is to build your app in such a manner.

We'd like to see gaia used by all users regardless of how they sign in. 

Hope that helps!

**Comment by jcnelson** [comment]
What happens if they use Blockstack Auth incorrectly?  For example, by hard-coding a redirect to browser.blockstack.org instead of using the protocol handler?

**Comment by larrysalibra** [comment]
> What happens if they use Blockstack Auth incorrectly? For example, by hard-coding a redirect to browser.blockstack.org instead of using the protocol handler?

Using Blockstack Auth incorrectly results in a broken score.

**Comment by jeffdomke** [comment]
Sounds like this is resolved. Moving to done.

**Comment by geeogi** [comment]
@jeffdomke yep. Thanks @larrysalibra for the clear and detailed answer 👍
