### ISSUE TITLE
Proposal: Change payouts formula to slanting step function

### ISSUE THREAD

**Issue by friedger** [blockstack/app-mining#80]
**What is the problem you are seeing? Please describe.**
App publishers ranking 25 and lower get less than 100$ paid out

**How is this problem misaligned with goals of app mining?**
This does not align with the goal to increase the number of apps.

**What is the explicit recommendation you’re looking to propose?**
The following payout algorithm is proposed:

1. **Calculate a base value for each rank**
The first rank receives 15.000$

For the rest the following formula is applied where A
=IF(LOG(RANK,2) = FLOOR(LOG(RANK,2)), 10000*2/RANK, AMOUNT_RANK_MINUS_ONE*(1-(2*POW(10,-FLOOR(LOG(RANK,2))))))

or in other words every power of 2 the award is divided by 2 and within these award blocks the one below received 20%, 2%, 0.2%,.. less than the one before 

1. **Calculate the new award for each rank depending on the number of apps submitted**

Calculate the **correcting factor** as monthly pot divided by sum of all base values for all apps. 

Then the **new award** for an app is: base value times correcting factor.

![Screenshot from 2019-03-24 14-21-03](https://user-images.githubusercontent.com/1449049/54879990-20ff8180-4e40-11e9-8e5b-7f7fe47e42f5.png)

** Describe your long term considerations in proposing this change. Please include the ways you can predict this recommendation could go wrong and possible ways mitigate.**

The new formula tries to keep a similar shape than the original algorithm.

With a monthly pot of 100k$ this gives
For 50 apps, a minimum payout of 600$, max payout of 14,000$
For 150 apps, a minimum payout of 115$, max payout of 11,000$
For 250 apps, a minimum payout of 103$, max payout of 9,900$
For 1000 apps, a minimum payout of 20$, max payout of 7,800$

This suggests that existing app publishers do not have an interest in onboarding new app publishers. However, with the new algorithm, the more app publishers onboard the more publishers benefit from a higher rate in comparison to the origin algorithm.

**Additional context**
#25 
A simulation can be found [here](https://docs.google.com/spreadsheets/d/18dCTukfuTYlMNjKRMVN6XsBDO9QyVRbq_4wl_VG0luY/edit?usp=sharing)

**Comment by GinaAbrams** [comment]
Would love more feedback from the community on this! Also minimum payouts and proposal discussed [here](https://github.com/blockstack/app-mining/issues/25#issuecomment-477299846).

**Comment by friedger** [comment]
Does it make sense do a simulation with 300k$ or what is the next step? @ginaAdam

**Comment by jeffdomke** [comment]
We're currently discussing this proposal and other changes to the payout amount and structure. Please stay tuned.

**Comment by friedger** [comment]
With the 3% of 1m STX reward scheme:
* the first 250 apps get more than 15 STX/month
* apps ranked 340 and lower get less than 1 STX

See https://docs.google.com/spreadsheets/d/1xQrGclubYJzYHVqUYxZqXXtkRTYQSrEJ1udA67OF0oY/edit#gid=0

**Comment by friedger** [comment]
Won't happen
