### ISSUE TITLE
TryMyUI: Improve app publisher happyness

### ISSUE THREAD

**Issue by friedger** [blockstack/app-mining#81]
After discussion in #71 the could be some improvements about TMUI:
* the documentation about the complaints procedure for TMUI should be added to the app reviewer page.
* The scenario/mind set should be changed towards "users that want these apps". Instead of 
>You heard about this website from a friend, and wanted to check it out for yourself. 

"You are scared about the market power of the big tech companies and you heard about this website from a friend that helps you to keep control of your data, and you wanted to check it out for yourself."

* TMUI uses the term "Blockstack sign-in". Either add "Blockstack login" in the instructions or document for app publishers that a authentication button should be labeled "Blockstack sign-in".

**Comment by friedger** [comment]
I have received several comments from the testers that 
* my app lacks features in comparison to existing products and 
* the security and privacy is not needed in their daily life

It does not make sense to sell my product to user who do not want them. If we can't solve #1 then at least their mind set should be set towards blockstack.

**Comment by GinaAbrams** [comment]
hey @friedger, 
> * the documentation about the complaints procedure for TMUI should be added to the app reviewer page.
>
>>

Do you mean the TryMyUI contact email, a link to this GitHub repo, or something else? 

> * The scenario/mind set should be changed towards "users that want these apps". Instead of
> 
> >

@jeffdomke will be rolling out an update on differentiated audiences that should help soon! 😃

**Comment by jeffdomke** [comment]
I think this is solved by issue #1 moving to done.
