### ISSUE TITLE
NIL: Adjust numbers used in calculation

### ISSUE THREAD

**Issue by jeffdomke** [blockstack/app-mining#83]
The current system -1, 0, 2, 4 messes up, or seems to mess up, the final math. Suggest we use something with single integer levels.

**Comment by jeffdomke** [comment]
@larrysalibra can you advise on this for April. I assume this change will be made in your rankings?

**Comment by larrysalibra** [comment]
We can use consecutive integers - my understanding from @hstove (correct me if i'm wrong) is that the specific numbers don't matter that much because of the way final scores are calculated.

**Comment by hstove** [comment]
> my understanding from @hstove (correct me if i'm wrong) is that the specific numbers don't matter that much because of the way final scores are calculated.

No, it doesn't matter that much, but it does make a slight difference. I'd advise for consecutive integers.

**Comment by jeffdomke** [comment]
@larrysalibra when we discussed this it sounds like this change makes sense, can you please give a clear yes or no.

**Comment by larrysalibra** [comment]
Yes
