### ISSUE TITLE
Proposal: Change Product Hunt ranking algorithm

### ISSUE THREAD

**Issue by hstove** [blockstack/app-mining#85]
For April 2019, we are going to do a dry run with the following changes to your Product Hunt score:

- Include a 90% monthly decay to your Product Hunt total upvotes. This will make a single big launch count less over time. Right now, if you got lucky with a great launch, it gives you a huge score forever. You can also re-hunt your app every ~6ish months if your app has significant changes.
- Include a new metric, which takes into account your number of new credible upvotes since last month.

**Comment by jeffdomke** [comment]
Sounds like this is good. Moving to done.

**Comment by radedoc** [comment]
Are you sure you mean a 90% monthly decay?  That would mean that only 10% of your product hunt votes carry on from month to month which would mean your product hunt votes go to 0 in a matter of 2 or 3 months.

**Comment by radedoc** [comment]
Not sure if you mean 10% month to month decay which sounds a lot more reasonable.

**Comment by hstove** [comment]
I think you're probably right - you get 90% of your votes from last month, or 10% go away.
