### ISSUE TITLE
Review all TryMyUI videos and DM apps with old blockstack.js

### ISSUE THREAD

**Issue by jeffdomke** [blockstack/app-mining#87]

**Comment by GinaAbrams** [comment]
@markmhx is working on an email but I think has also DMd -- is this issue still relevant?

**Comment by markmhx** [comment]
We could go the extra mile and directly contact the developers of non-upgraded apps, but I've emailed all developers about it in bulk just today so we could also wait to see the effect in April videos.

**Comment by jeffdomke** [comment]
Thanks @markmhx sounds like everyone was emailed and also @larrysalibra is also catching these with the digital rights reviewer. Closing this issue.
