### ISSUE TITLE
Create a page for each reviewer in `app-reviewers`

### ISSUE THREAD

**Issue by hstove** [blockstack/app-mining#89]
We already have a page for TryMyUI. We should have a page for each reviewer, and have info about scoring and process. We can update the README to link to these pages.

**Comment by moxiegirl** [comment]
@hstove We already have documentation for the reviews in the actual documentation. @GinaAbrams I'm not sure it makes sense to keep this information in two places. There will be drift between what is published in the docs and what is in the repository.

**Comment by friedger** [comment]
I think we can have the two places:
1. Docs for developers to learn about the app reviewers, introduction (stable, high level)
1. Docs for details about the score generation or information that is relevant for that and that can be discussed here. These docs should reference the introduction only, not copy it.

**Comment by friedger** [comment]
It was decided to keep all information about app reviewers on docs.blockstack.org

**Comment by friedger** [comment]
@jeffdomke This can be closed.
