### ISSUE TITLE
Reviewer: Can evaluate based on user growth of blockstack IDs

### ISSUE THREAD

**Issue by jeffdomke** [blockstack/app-mining#9]

**Comment by pstan26** [comment]
Would this be for all non-subdomain IDs? Otherwise this feels gameable .

**Comment by jeffdomke** [comment]
Yeah, basically the same thing reported on theblockstats and it would indeed be super gameable.

**Comment by friedger** [comment]
@jeffdomke Could be closed, couldn't it?
