### ISSUE TITLE
Upgrading TryMyUI scores

### ISSUE THREAD

**Issue by jeffdomke** [blockstack/app-mining#90]
- ~Blending 25% of this months score with last months~
- Making the # of testers 10 [Confirmed done ✔️]

**Comment by jeffdomke** [comment]
Sounds like next step is to ask Tim

**Comment by friedger** [comment]
That is good! Currently, the same app (without changes) has quite different values for different months.

**Comment by jeffdomke** [comment]
TryMyUI added 10 testers and we decided not to pursue an additional memory function specific to TryMyUI so I am closing this.

**Comment by jeffdomke** [comment]
Killed the blending thing and we already have the 10 testers. Done!
