### ISSUE TITLE
Pause Democracy Earth Investor Community App Reviewer 

### ISSUE THREAD

**Issue by GinaAbrams** [blockstack/app-mining#92]
We have seen multiple issues arise with some of the challenges presented by involving the Token holding community as voters (e.g. #72 and #66) but the biggest questions are around voter engagement and incentives. The concept is great in principle, and the Democracy Earth team has been an incredible partner with many exciting projects ahead. But the open questions could take many months of research to properly solve. We are most interested in moving App Mining forward in the most equitable way possible. In this [forum post](https://forum.blockstack.org/t/app-mining-improvement-proposal-pause-democracy-earth-as-investor-community-app-reviewer/7903), we propose pausing Democracy Earth as an app reviewer. Thoughts and feedback welcome.

**Comment by friedger** [comment]
Makes sense!

**Comment by kkomaz** [comment]
I would have to agree in pausing democracy earth.  There isn't enough engagement from the investor side and is not a great representation of the full breadth of "token" holders

**Comment by felimadu** [comment]
I am in full support of this!

**Comment by jyudkin1** [comment]
I support it - unless there is a way to make a fix or drive engagement up. It is a great signal, but unfortunately it doesn't seem like it is ongoing from the voters.

**Comment by GinaAbrams** [comment]
Thanks to everyone for the review and input. We are proceeding with pausing Democracy Earth as a reviewer starting in May.
