### ISSUE TITLE
TryMyUI videos open to public

### ISSUE THREAD

**Issue by kkomaz** [blockstack/app-mining#94]
**What is the problem you are seeing? Please describe.**
Currently you are only allowed to watch your own videos on trymyui.  Although a good resource, we as developers are experiencing pain points with these testers whether it’s lack of familiarity with tech, experience, etc.  To help improve all apps overall it would be good to see all videos on trymui.  This would give lower ranked apps a good idea what top apps are doing right and help the overall ecosystem.

**How is this problem misaligned with goals of app mining**
It shouldn’t.

**What is the explicit recommendation you’re looking to propose?**
Make all TryMyUI videos public.

**Describe your long term considerations in proposing this change. Please include the ways you can predict this recommendation could go wrong and possible ways mitigate.**
This should overall be beneficial for all apps in the long term.  It could also help point out flaws in the testing phase that could occur in other apps which we can identify in this forum.  

Possible issues could be exposing tester names in the wild but can be mitigated via a storage file location only exposed to the devs themselves.

**Comment by dantrevino** [comment]
I love this idea, but have the same misgivings that @friedger mentioned in slack.  Tester emails are sometimes used in signup/forms and I'm not sure we'd wanna make those public.

**Comment by kkomaz** [comment]
@pstan26  // @dantrevino 

From my understanding blockstack watches all the videos to make sure the on boarding process is satisfactory.

If we had a private storage file location for app developers would that suffice?

**Comment by kkomaz** [comment]
This would also allow developers to audit other apps to alarm any red flags that might go against the spirit of blockstack app mining

**Comment by thedavidlewis** [comment]
> @pstan26 // @dantrevino
> 
> If we had a private storage file location for app developers to view the videos would that suffice?

I'm not sure how that is any different and it seems to go against the data privacy and ownership ethos of Blockstack. There would have to be a way to hide any personal information the user exposes in the video. If someone is entering private information that will be stored using Gaia, how can we allow that to be seen by even hundreds of Blockstack dapp developers?

**Comment by jeffdomke** [comment]
PBC team discussed and we don't want to decide for each app to reveal their user testing data. There is nothing blocking individual apps from sharing their videos or creating a forum to do so. Moving to done.
