### ISSUE TITLE
Use labels in this repo

### ISSUE THREAD

**Issue by friedger** [blockstack/app-mining#97]
The following labels should be used:
- meta (for issues about using github, managing requests, etc. This issue should have label `meta`)
- question
- reviewer-proposed, reviewer-comment-period, reviewer-in-progress, reviewer-announced (for issues proposing new reviewers or changes to existing reviewers)
- app (for issues related to a single app)
- docs (for issues related to files, documents in this repo, not for issue of docs.blockstack.org)
- opinion (for issues describing subjective aspects of the app mining process)

**Comment by moxiegirl** [comment]
@friedger Hi, thanks for this. We have updated this repo to use the standard labels we are applying to all our repos.

**Comment by friedger** [comment]
@moxiegirl I don't think that they match very well the need of this repo, but most importantly is that and how they are used :-)

**Comment by friedger** [comment]
Please reopen this issue, only one label is used once.
